project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

"preserve_hierarchy": true

"files": [
  {
    "source": "resources/lang/en.json",
    "translation": "resources/lang/%two_letters_code%.json"
  }
]
