services:
  photobooth:
    build: .
    ports:
        - "${HTTP_PORT:-80}:80"
        - "${HTTPS_PORT:-443}:443"
    environment:
      - COMPOSER_VERSION=2
    volumes:
      - ./private:/app/private
      - ./config:/app/config
      - ./data:/app/data
      - ./var:/app/var
