<?php

declare(strict_types=1);

namespace Photobooth\Enum;

use Photobooth\Enum\Interface\LabelInterface;

enum TimezoneEnum: string implements LabelInterface
{
    case AMERICA_ADAK = 'America/Adak';
    case AMERICA_ATKA = 'America/Atka';
    case AMERICA_ANCHORAGE = 'America/Anchorage';
    case AMERICA_JUNEAU = 'America/Juneau';
    case AMERICA_NOME = 'America/Nome';
    case AMERICA_YAKUTAT = 'America/Yakutat';
    case AMERICA_DAWSON = 'America/Dawson';
    case AMERICA_ENSENADA = 'America/Ensenada';
    case AMERICA_LOS_ANGELES = 'America/Los_Angeles';
    case AMERICA_TIJUANA = 'America/Tijuana';
    case AMERICA_VANCOUVER = 'America/Vancouver';
    case AMERICA_WHITEHORSE = 'America/Whitehorse';
    case CANADA_PACIFIC = 'Canada/Pacific';
    case CANADA_YUKON = 'Canada/Yukon';
    case MEXICO_BAJANORTE = 'Mexico/BajaNorte';
    case AMERICA_BOISE = 'America/Boise';
    case AMERICA_CAMBRIDGE_BAY = 'America/Cambridge_Bay';
    case AMERICA_CHIHUAHUA = 'America/Chihuahua';
    case AMERICA_DAWSON_CREEK = 'America/Dawson_Creek';
    case AMERICA_DENVER = 'America/Denver';
    case AMERICA_EDMONTON = 'America/Edmonton';
    case AMERICA_HERMOSILLO = 'America/Hermosillo';
    case AMERICA_INUVIK = 'America/Inuvik';
    case AMERICA_MAZATLAN = 'America/Mazatlan';
    case AMERICA_PHOENIX = 'America/Phoenix';
    case AMERICA_SHIPROCK = 'America/Shiprock';
    case AMERICA_YELLOWKNIFE = 'America/Yellowknife';
    case CANADA_MOUNTAIN = 'Canada/Mountain';
    case MEXICO_BAJASUR = 'Mexico/BajaSur';
    case AMERICA_BELIZE = 'America/Belize';
    case AMERICA_CANCUN = 'America/Cancun';
    case AMERICA_CHICAGO = 'America/Chicago';
    case AMERICA_COSTA_RICA = 'America/Costa_Rica';
    case AMERICA_EL_SALVADOR = 'America/El_Salvador';
    case AMERICA_GUATEMALA = 'America/Guatemala';
    case AMERICA_KNOX_IN = 'America/Knox_IN';
    case AMERICA_MANAGUA = 'America/Managua';
    case AMERICA_MENOMINEE = 'America/Menominee';
    case AMERICA_MERIDA = 'America/Merida';
    case AMERICA_MEXICO_CITY = 'America/Mexico_City';
    case AMERICA_MONTERREY = 'America/Monterrey';
    case AMERICA_RAINY_RIVER = 'America/Rainy_River';
    case AMERICA_RANKIN_INLET = 'America/Rankin_Inlet';
    case AMERICA_REGINA = 'America/Regina';
    case AMERICA_SWIFT_CURRENT = 'America/Swift_Current';
    case AMERICA_TEGUCIGALPA = 'America/Tegucigalpa';
    case AMERICA_WINNIPEG = 'America/Winnipeg';
    case CANADA_CENTRAL = 'Canada/Central';
    case CANADA_EAST_SASKATCHEWAN = 'Canada/East-Saskatchewan';
    case CANADA_SASKATCHEWAN = 'Canada/Saskatchewan';
    case CHILE_EASTERISLAND = 'Chile/EasterIsland';
    case MEXICO_GENERAL = 'Mexico/General';
    case AMERICA_ATIKOKAN = 'America/Atikokan';
    case AMERICA_BOGOTA = 'America/Bogota';
    case AMERICA_CAYMAN = 'America/Cayman';
    case AMERICA_CORAL_HARBOUR = 'America/Coral_Harbour';
    case AMERICA_DETROIT = 'America/Detroit';
    case AMERICA_FORT_WAYNE = 'America/Fort_Wayne';
    case AMERICA_GRAND_TURK = 'America/Grand_Turk';
    case AMERICA_GUAYAQUIL = 'America/Guayaquil';
    case AMERICA_HAVANA = 'America/Havana';
    case AMERICA_INDIANAPOLIS = 'America/Indianapolis';
    case AMERICA_IQALUIT = 'America/Iqaluit';
    case AMERICA_JAMAICA = 'America/Jamaica';
    case AMERICA_LIMA = 'America/Lima';
    case AMERICA_LOUISVILLE = 'America/Louisville';
    case AMERICA_MONTREAL = 'America/Montreal';
    case AMERICA_NASSAU = 'America/Nassau';
    case AMERICA_NEW_YORK = 'America/New_York';
    case AMERICA_NIPIGON = 'America/Nipigon';
    case AMERICA_PANAMA = 'America/Panama';
    case AMERICA_PANGNIRTUNG = 'America/Pangnirtung';
    case AMERICA_PORT_AU_PRINCE = 'America/Port-au-Prince';
    case AMERICA_RESOLUTE = 'America/Resolute';
    case AMERICA_THUNDER_BAY = 'America/Thunder_Bay';
    case AMERICA_TORONTO = 'America/Toronto';
    case CANADA_EASTERN = 'Canada/Eastern';
    case AMERICA_CARACAS = 'America/Caracas';
    case AMERICA_ANGUILLA = 'America/Anguilla';
    case AMERICA_ANTIGUA = 'America/Antigua';
    case AMERICA_ARUBA = 'America/Aruba';
    case AMERICA_ASUNCION = 'America/Asuncion';
    case AMERICA_BARBADOS = 'America/Barbados';
    case AMERICA_BLANC_SABLON = 'America/Blanc-Sablon';
    case AMERICA_BOA_VISTA = 'America/Boa_Vista';
    case AMERICA_CAMPO_GRANDE = 'America/Campo_Grande';
    case AMERICA_CUIABA = 'America/Cuiaba';
    case AMERICA_CURACAO = 'America/Curacao';
    case AMERICA_DOMINICA = 'America/Dominica';
    case AMERICA_EIRUNEPE = 'America/Eirunepe';
    case AMERICA_GLACE_BAY = 'America/Glace_Bay';
    case AMERICA_GOOSE_BAY = 'America/Goose_Bay';
    case AMERICA_GRENADA = 'America/Grenada';
    case AMERICA_GUADELOUPE = 'America/Guadeloupe';
    case AMERICA_GUYANA = 'America/Guyana';
    case AMERICA_HALIFAX = 'America/Halifax';
    case AMERICA_LA_PAZ = 'America/La_Paz';
    case AMERICA_MANAUS = 'America/Manaus';
    case AMERICA_MARIGOT = 'America/Marigot';
    case AMERICA_MARTINIQUE = 'America/Martinique';
    case AMERICA_MONCTON = 'America/Moncton';
    case AMERICA_MONTSERRAT = 'America/Montserrat';
    case AMERICA_PORT_OF_SPAIN = 'America/Port_of_Spain';
    case AMERICA_PORTO_ACRE = 'America/Porto_Acre';
    case AMERICA_PORTO_VELHO = 'America/Porto_Velho';
    case AMERICA_PUERTO_RICO = 'America/Puerto_Rico';
    case AMERICA_RIO_BRANCO = 'America/Rio_Branco';
    case AMERICA_SANTIAGO = 'America/Santiago';
    case AMERICA_SANTO_DOMINGO = 'America/Santo_Domingo';
    case AMERICA_ST_BARTHELEMY = 'America/St_Barthelemy';
    case AMERICA_ST_KITTS = 'America/St_Kitts';
    case AMERICA_ST_LUCIA = 'America/St_Lucia';
    case AMERICA_ST_THOMAS = 'America/St_Thomas';
    case AMERICA_ST_VINCENT = 'America/St_Vincent';
    case AMERICA_THULE = 'America/Thule';
    case AMERICA_TORTOLA = 'America/Tortola';
    case AMERICA_VIRGIN = 'America/Virgin';
    case ANTARCTICA_PALMER = 'Antarctica/Palmer';
    case ATLANTIC_BERMUDA = 'Atlantic/Bermuda';
    case ATLANTIC_STANLEY = 'Atlantic/Stanley';
    case BRAZIL_ACRE = 'Brazil/Acre';
    case BRAZIL_WEST = 'Brazil/West';
    case CANADA_ATLANTIC = 'Canada/Atlantic';
    case CHILE_CONTINENTAL = 'Chile/Continental';
    case AMERICA_ST_JOHNS = 'America/St_Johns';
    case CANADA_NEWFOUNDLAND = 'Canada/Newfoundland';
    case AMERICA_ARAGUAINA = 'America/Araguaina';
    case AMERICA_BAHIA = 'America/Bahia';
    case AMERICA_BELEM = 'America/Belem';
    case AMERICA_BUENOS_AIRES = 'America/Buenos_Aires';
    case AMERICA_CATAMARCA = 'America/Catamarca';
    case AMERICA_CAYENNE = 'America/Cayenne';
    case AMERICA_CORDOBA = 'America/Cordoba';
    case AMERICA_FORTALEZA = 'America/Fortaleza';
    case AMERICA_GODTHAB = 'America/Godthab';
    case AMERICA_JUJUY = 'America/Jujuy';
    case AMERICA_MACEIO = 'America/Maceio';
    case AMERICA_MENDOZA = 'America/Mendoza';
    case AMERICA_MIQUELON = 'America/Miquelon';
    case AMERICA_MONTEVIDEO = 'America/Montevideo';
    case AMERICA_PARAMARIBO = 'America/Paramaribo';
    case AMERICA_RECIFE = 'America/Recife';
    case AMERICA_ROSARIO = 'America/Rosario';
    case AMERICA_SANTAREM = 'America/Santarem';
    case AMERICA_SAO_PAULO = 'America/Sao_Paulo';
    case ANTARCTICA_ROTHERA = 'Antarctica/Rothera';
    case BRAZIL_EAST = 'Brazil/East';
    case AMERICA_NORONHA = 'America/Noronha';
    case ATLANTIC_SOUTH_GEORGIA = 'Atlantic/South_Georgia';
    case BRAZIL_DENORONHA = 'Brazil/DeNoronha';
    case AMERICA_SCORESBYSUND = 'America/Scoresbysund';
    case ATLANTIC_AZORES = 'Atlantic/Azores';
    case ATLANTIC_CAPE_VERDE = 'Atlantic/Cape_Verde';
    case AFRICA_ABIDJAN = 'Africa/Abidjan';
    case AFRICA_ACCRA = 'Africa/Accra';
    case AFRICA_BAMAKO = 'Africa/Bamako';
    case AFRICA_BANJUL = 'Africa/Banjul';
    case AFRICA_BISSAU = 'Africa/Bissau';
    case AFRICA_CASABLANCA = 'Africa/Casablanca';
    case AFRICA_CONAKRY = 'Africa/Conakry';
    case AFRICA_DAKAR = 'Africa/Dakar';
    case AFRICA_EL_AAIUN = 'Africa/El_Aaiun';
    case AFRICA_FREETOWN = 'Africa/Freetown';
    case AFRICA_LOME = 'Africa/Lome';
    case AFRICA_MONROVIA = 'Africa/Monrovia';
    case AFRICA_NOUAKCHOTT = 'Africa/Nouakchott';
    case AFRICA_OUAGADOUGOU = 'Africa/Ouagadougou';
    case AFRICA_SAO_TOME = 'Africa/Sao_Tome';
    case AFRICA_TIMBUKTU = 'Africa/Timbuktu';
    case AMERICA_DANMARKSHAVN = 'America/Danmarkshavn';
    case ATLANTIC_CANARY = 'Atlantic/Canary';
    case ATLANTIC_FAEROE = 'Atlantic/Faeroe';
    case ATLANTIC_FAROE = 'Atlantic/Faroe';
    case ATLANTIC_MADEIRA = 'Atlantic/Madeira';
    case ATLANTIC_REYKJAVIK = 'Atlantic/Reykjavik';
    case ATLANTIC_ST_HELENA = 'Atlantic/St_Helena';
    case EUROPE_BELFAST = 'Europe/Belfast';
    case EUROPE_DUBLIN = 'Europe/Dublin';
    case EUROPE_GUERNSEY = 'Europe/Guernsey';
    case EUROPE_ISLE_OF_MAN = 'Europe/Isle_of_Man';
    case EUROPE_JERSEY = 'Europe/Jersey';
    case EUROPE_LISBON = 'Europe/Lisbon';
    case EUROPE_LONDON = 'Europe/London';
    case AFRICA_ALGIERS = 'Africa/Algiers';
    case AFRICA_BANGUI = 'Africa/Bangui';
    case AFRICA_BRAZZAVILLE = 'Africa/Brazzaville';
    case AFRICA_CEUTA = 'Africa/Ceuta';
    case AFRICA_DOUALA = 'Africa/Douala';
    case AFRICA_KINSHASA = 'Africa/Kinshasa';
    case AFRICA_LAGOS = 'Africa/Lagos';
    case AFRICA_LIBREVILLE = 'Africa/Libreville';
    case AFRICA_LUANDA = 'Africa/Luanda';
    case AFRICA_MALABO = 'Africa/Malabo';
    case AFRICA_NDJAMENA = 'Africa/Ndjamena';
    case AFRICA_NIAMEY = 'Africa/Niamey';
    case AFRICA_PORTO_NOVO = 'Africa/Porto-Novo';
    case AFRICA_TUNIS = 'Africa/Tunis';
    case AFRICA_WINDHOEK = 'Africa/Windhoek';
    case ARCTIC_LONGYEARBYEN = 'Arctic/Longyearbyen';
    case ATLANTIC_JAN_MAYEN = 'Atlantic/Jan_Mayen';
    case EUROPE_AMSTERDAM = 'Europe/Amsterdam';
    case EUROPE_ANDORRA = 'Europe/Andorra';
    case EUROPE_BELGRADE = 'Europe/Belgrade';
    case EUROPE_BERLIN = 'Europe/Berlin';
    case EUROPE_BRATISLAVA = 'Europe/Bratislava';
    case EUROPE_BRUSSELS = 'Europe/Brussels';
    case EUROPE_BUDAPEST = 'Europe/Budapest';
    case EUROPE_COPENHAGEN = 'Europe/Copenhagen';
    case EUROPE_GIBRALTAR = 'Europe/Gibraltar';
    case EUROPE_LJUBLJANA = 'Europe/Ljubljana';
    case EUROPE_LUXEMBOURG = 'Europe/Luxembourg';
    case EUROPE_MADRID = 'Europe/Madrid';
    case EUROPE_MALTA = 'Europe/Malta';
    case EUROPE_MONACO = 'Europe/Monaco';
    case EUROPE_OSLO = 'Europe/Oslo';
    case EUROPE_PARIS = 'Europe/Paris';
    case EUROPE_PODGORICA = 'Europe/Podgorica';
    case EUROPE_PRAGUE = 'Europe/Prague';
    case EUROPE_ROME = 'Europe/Rome';
    case EUROPE_SAN_MARINO = 'Europe/San_Marino';
    case EUROPE_SARAJEVO = 'Europe/Sarajevo';
    case EUROPE_SKOPJE = 'Europe/Skopje';
    case EUROPE_STOCKHOLM = 'Europe/Stockholm';
    case EUROPE_TIRANE = 'Europe/Tirane';
    case EUROPE_VADUZ = 'Europe/Vaduz';
    case EUROPE_VATICAN = 'Europe/Vatican';
    case EUROPE_VIENNA = 'Europe/Vienna';
    case EUROPE_WARSAW = 'Europe/Warsaw';
    case EUROPE_ZAGREB = 'Europe/Zagreb';
    case EUROPE_ZURICH = 'Europe/Zurich';
    case AFRICA_BLANTYRE = 'Africa/Blantyre';
    case AFRICA_BUJUMBURA = 'Africa/Bujumbura';
    case AFRICA_CAIRO = 'Africa/Cairo';
    case AFRICA_GABORONE = 'Africa/Gaborone';
    case AFRICA_HARARE = 'Africa/Harare';
    case AFRICA_JOHANNESBURG = 'Africa/Johannesburg';
    case AFRICA_KIGALI = 'Africa/Kigali';
    case AFRICA_LUBUMBASHI = 'Africa/Lubumbashi';
    case AFRICA_LUSAKA = 'Africa/Lusaka';
    case AFRICA_MAPUTO = 'Africa/Maputo';
    case AFRICA_MASERU = 'Africa/Maseru';
    case AFRICA_MBABANE = 'Africa/Mbabane';
    case AFRICA_TRIPOLI = 'Africa/Tripoli';
    case ASIA_AMMAN = 'Asia/Amman';
    case ASIA_BEIRUT = 'Asia/Beirut';
    case ASIA_DAMASCUS = 'Asia/Damascus';
    case ASIA_GAZA = 'Asia/Gaza';
    case ASIA_ISTANBUL = 'Asia/Istanbul';
    case ASIA_JERUSALEM = 'Asia/Jerusalem';
    case ASIA_NICOSIA = 'Asia/Nicosia';
    case ASIA_TEL_AVIV = 'Asia/Tel_Aviv';
    case EUROPE_ATHENS = 'Europe/Athens';
    case EUROPE_BUCHAREST = 'Europe/Bucharest';
    case EUROPE_CHISINAU = 'Europe/Chisinau';
    case EUROPE_HELSINKI = 'Europe/Helsinki';
    case EUROPE_KALININGRAD = 'Europe/Kaliningrad';
    case EUROPE_KIEV = 'Europe/Kiev';
    case EUROPE_MARIEMAN = 'Europe/Mariehamn';
    case EUROPE_MINSK = 'Europe/Minsk';
    case EUROPE_NICOSIA = 'Europe/Nicosia';
    case EUROPE_RIGA = 'Europe/Riga';
    case EUROPE_SIMFEROPOL = 'Europe/Simferopol';
    case EUROPE_SOFIA = 'Europe/Sofia';
    case EUROPE_TALLINN = 'Europe/Tallinn';
    case EUROPE_TIRASPOL = 'Europe/Tiraspol';
    case EUROPE_UZHGOROD = 'Europe/Uzhgorod';
    case EUROPE_VILNIUS = 'Europe/Vilnius';
    case EUROPE_ZAPOROZHYE = 'Europe/Zaporozhye';
    case AFRICA_ADDIS_ABABA = 'Africa/Addis_Ababa';
    case AFRICA_ASMARA = 'Africa/Asmara';
    case AFRICA_ASMERA = 'Africa/Asmera';
    case AFRICA_DAR_ES_SALAAM = 'Africa/Dar_es_Salaam';
    case AFRICA_DJIBOUTI = 'Africa/Djibouti';
    case AFRICA_KAMPALA = 'Africa/Kampala';
    case AFRICA_KHARTOUM = 'Africa/Khartoum';
    case AFRICA_MOGADISHU = 'Africa/Mogadishu';
    case AFRICA_NAIROBI = 'Africa/Nairobi';
    case ANTARCTICA_SYOWA = 'Antarctica/Syowa';
    case ASIA_ADEN = 'Asia/Aden';
    case ASIA_BAGHDAD = 'Asia/Baghdad';
    case ASIA_BAHRAIN = 'Asia/Bahrain';
    case ASIA_KUWAIT = 'Asia/Kuwait';
    case ASIA_QATAR = 'Asia/Qatar';
    case EUROPE_MOSCOW = 'Europe/Moscow';
    case EUROPE_VOLGOGRAD = 'Europe/Volgograd';
    case INDIAN_ANTANANARIVO = 'Indian/Antananarivo';
    case INDIAN_COMORO = 'Indian/Comoro';
    case INDIAN_MAYOTTE = 'Indian/Mayotte';
    case ASIA_TEHRAN = 'Asia/Tehran';
    case ASIA_BAKU = 'Asia/Baku';
    case ASIA_DUBAI = 'Asia/Dubai';
    case ASIA_MUSCAT = 'Asia/Muscat';
    case ASIA_TBILISI = 'Asia/Tbilisi';
    case ASIA_YEREVAN = 'Asia/Yerevan';
    case EUROPE_SAMARA = 'Europe/Samara';
    case INDIAN_MAHE = 'Indian/Mahe';
    case INDIAN_MAURITIUS = 'Indian/Mauritius';
    case INDIAN_REUNION = 'Indian/Reunion';
    case ASIA_KABUL = 'Asia/Kabul';
    case ASIA_AQTAU = 'Asia/Aqtau';
    case ASIA_AQTOBE = 'Asia/Aqtobe';
    case ASIA_ASHGABAT = 'Asia/Ashgabat';
    case ASIA_ASHKHABAD = 'Asia/Ashkhabad';
    case ASIA_DUSHANBE = 'Asia/Dushanbe';
    case ASIA_KARACHI = 'Asia/Karachi';
    case ASIA_ORAL = 'Asia/Oral';
    case ASIA_SAMARKAND = 'Asia/Samarkand';
    case ASIA_TASHKENT = 'Asia/Tashkent';
    case ASIA_YEKATERINBURG = 'Asia/Yekaterinburg';
    case INDIAN_KERGUELEN = 'Indian/Kerguelen';
    case INDIAN_MALDIVES = 'Indian/Maldives';
    case ASIA_CALCUTTA = 'Asia/Calcutta';
    case ASIA_COLOMBO = 'Asia/Colombo';
    case ASIA_KOLKATA = 'Asia/Kolkata';
    case ASIA_KATMANDU = 'Asia/Katmandu';
    case ANTARCTICA_MAWSON = 'Antarctica/Mawson';
    case ANTARCTICA_VOSTOK = 'Antarctica/Vostok';
    case ASIA_ALMATY = 'Asia/Almaty';
    case ASIA_BISHKEK = 'Asia/Bishkek';
    case ASIA_DACCA = 'Asia/Dacca';
    case ASIA_DHAKA = 'Asia/Dhaka';
    case ASIA_NOVOSIBIRSK = 'Asia/Novosibirsk';
    case ASIA_OMSK = 'Asia/Omsk';
    case ASIA_QYZYLORDA = 'Asia/Qyzylorda';
    case ASIA_THIMBU = 'Asia/Thimbu';
    case ASIA_THIMPHU = 'Asia/Thimphu';
    case INDIAN_CHAGOS = 'Indian/Chagos';
    case ASIA_RANGOON = 'Asia/Rangoon';
    case INDIAN_COCOS = 'Indian/Cocos';
    case ANTARCTICA_DAVIS = 'Antarctica/Davis';
    case ASIA_BANGKOK = 'Asia/Bangkok';
    case ASIA_HO_CHI_MINH = 'Asia/Ho_Chi_Minh';
    case ASIA_HOVD = 'Asia/Hovd';
    case ASIA_JAKARTA = 'Asia/Jakarta';
    case ASIA_KRASNOYARSK = 'Asia/Krasnoyarsk';
    case ASIA_PHNOM_PENH = 'Asia/Phnom_Penh';
    case ASIA_PONTIANAK = 'Asia/Pontianak';
    case ASIA_SAIGON = 'Asia/Saigon';
    case ASIA_VIENTIANE = 'Asia/Vientiane';
    case INDIAN_CHRISTMAS = 'Indian/Christmas';
    case ANTARCTICA_CASEY = 'Antarctica/Casey';
    case ASIA_BRUNEI = 'Asia/Brunei';
    case ASIA_CHOIBALSAN = 'Asia/Choibalsan';
    case ASIA_CHONGQING = 'Asia/Chongqing';
    case ASIA_CHUNGKING = 'Asia/Chungking';
    case ASIA_HARBIN = 'Asia/Harbin';
    case ASIA_HONG_KONG = 'Asia/Hong_Kong';
    case ASIA_IRKUTSK = 'Asia/Irkutsk';
    case ASIA_KASHGAR = 'Asia/Kashgar';
    case ASIA_KUALA_LUMPUR = 'Asia/Kuala_Lumpur';
    case ASIA_KUCHING = 'Asia/Kuching';
    case ASIA_MACAO = 'Asia/Macao';
    case ASIA_MACAU = 'Asia/Macau';
    case ASIA_MAKASSAR = 'Asia/Makassar';
    case ASIA_MANILA = 'Asia/Manila';
    case ASIA_SHANGHAI = 'Asia/Shanghai';
    case ASIA_SINGAPORE = 'Asia/Singapore';
    case ASIA_TAIPEI = 'Asia/Taipei';
    case ASIA_UJUNG_PANDANG = 'Asia/Ujung_Pandang';
    case ASIA_ULAANBAATAR = 'Asia/Ulaanbaatar';
    case ASIA_ULAN_BATOR = 'Asia/Ulan_Bator';
    case ASIA_URUMQI = 'Asia/Urumqi';
    case AUSTRALIA_PERTH = 'Australia/Perth';
    case AUSTRALIA_WEST = 'Australia/West';
    case AUSTRALIA_EUCLA = 'Australia/Eucla';
    case ASIA_DILI = 'Asia/Dili';
    case ASIA_JAYAPURA = 'Asia/Jayapura';
    case ASIA_PYONGYANG = 'Asia/Pyongyang';
    case ASIA_SEOUL = 'Asia/Seoul';
    case ASIA_TOKYO = 'Asia/Tokyo';
    case ASIA_YAKUTSK = 'Asia/Yakutsk';
    case AUSTRALIA_ADELAIDE = 'Australia/Adelaide';
    case AUSTRALIA_BROKEN_HILL = 'Australia/Broken_Hill';
    case AUSTRALIA_DARWIN = 'Australia/Darwin';
    case AUSTRALIA_NORTH = 'Australia/North';
    case AUSTRALIA_SOUTH = 'Australia/South';
    case AUSTRALIA_YANCOWINNA = 'Australia/Yancowinna';
    case ANTARCTICA_DUMONT_DURVILLE = 'Antarctica/DumontDUrville';
    case ASIA_SAKHALIN = 'Asia/Sakhalin';
    case ASIA_VLADIVOSTOK = 'Asia/Vladivostok';
    case AUSTRALIA_ACT = 'Australia/ACT';
    case AUSTRALIA_BRISBANE = 'Australia/Brisbane';
    case AUSTRALIA_CANBERRA = 'Australia/Canberra';
    case AUSTRALIA_CURRIE = 'Australia/Currie';
    case AUSTRALIA_HOBART = 'Australia/Hobart';
    case AUSTRALIA_LINDEMAN = 'Australia/Lindeman';
    case AUSTRALIA_MELBOURNE = 'Australia/Melbourne';
    case AUSTRALIA_NSW = 'Australia/NSW';
    case AUSTRALIA_QUEENSLAND = 'Australia/Queensland';
    case AUSTRALIA_SYDNEY = 'Australia/Sydney';
    case AUSTRALIA_TASMANIA = 'Australia/Tasmania';
    case AUSTRALIA_VICTORIA = 'Australia/Victoria';
    case AUSTRALIA_LHI = 'Australia/LHI';
    case AUSTRALIA_LORD_HOWE = 'Australia/Lord_Howe';
    case ASIA_MAGADAN = 'Asia/Magadan';
    case ANTARCTICA_MCMURDO = 'Antarctica/McMurdo';
    case ANTARCTICA_SOUTH_POLE = 'Antarctica/South_Pole';
    case ASIA_ANADYR = 'Asia/Anadyr';
    case ASIA_KAMCHATKA = 'Asia/Kamchatka';

    public function label(): string
    {
        return match ($this) {
            self::AMERICA_ADAK => '(GMT-10:00) America/Adak (Hawaii-Aleutian Standard Time)',
            self::AMERICA_ATKA => '(GMT-10:00) America/Atka (Hawaii-Aleutian Standard Time)',
            self::AMERICA_ANCHORAGE => '(GMT-9:00) America/Anchorage (Alaska Standard Time)',
            self::AMERICA_JUNEAU => '(GMT-9:00) America/Juneau (Alaska Standard Time)',
            self::AMERICA_NOME => '(GMT-9:00) America/Nome (Alaska Standard Time)',
            self::AMERICA_YAKUTAT => '(GMT-9:00) America/Yakutat (Alaska Standard Time)',
            self::AMERICA_DAWSON => '(GMT-8:00) America/Dawson (Pacific Standard Time)',
            self::AMERICA_ENSENADA => '(GMT-8:00) America/Ensenada (Pacific Standard Time)',
            self::AMERICA_LOS_ANGELES => '(GMT-8:00) America/Los_Angeles (Pacific Standard Time)',
            self::AMERICA_TIJUANA => '(GMT-8:00) America/Tijuana (Pacific Standard Time)',
            self::AMERICA_VANCOUVER => '(GMT-8:00) America/Vancouver (Pacific Standard Time)',
            self::AMERICA_WHITEHORSE => '(GMT-8:00) America/Whitehorse (Pacific Standard Time)',
            self::CANADA_PACIFIC => '(GMT-8:00) Canada/Pacific (Pacific Standard Time)',
            self::CANADA_YUKON => '(GMT-8:00) Canada/Yukon (Pacific Standard Time)',
            self::MEXICO_BAJANORTE => '(GMT-8:00) Mexico/BajaNorte (Pacific Standard Time)',
            self::AMERICA_BOISE => '(GMT-7:00) America/Boise (Mountain Standard Time)',
            self::AMERICA_CAMBRIDGE_BAY => '(GMT-7:00) America/Cambridge_Bay (Mountain Standard Time)',
            self::AMERICA_CHIHUAHUA => '(GMT-7:00) America/Chihuahua (Mountain Standard Time)',
            self::AMERICA_DAWSON_CREEK => '(GMT-7:00) America/Dawson_Creek (Mountain Standard Time)',
            self::AMERICA_DENVER => '(GMT-7:00) America/Denver (Mountain Standard Time)',
            self::AMERICA_EDMONTON => '(GMT-7:00) America/Edmonton (Mountain Standard Time)',
            self::AMERICA_HERMOSILLO => '(GMT-7:00) America/Hermosillo (Mountain Standard Time)',
            self::AMERICA_INUVIK => '(GMT-7:00) America/Inuvik (Mountain Standard Time)',
            self::AMERICA_MAZATLAN => '(GMT-7:00) America/Mazatlan (Mountain Standard Time)',
            self::AMERICA_PHOENIX => '(GMT-7:00) America/Phoenix (Mountain Standard Time)',
            self::AMERICA_SHIPROCK => '(GMT-7:00) America/Shiprock (Mountain Standard Time)',
            self::AMERICA_YELLOWKNIFE => '(GMT-7:00) America/Yellowknife (Mountain Standard Time)',
            self::CANADA_MOUNTAIN => '(GMT-7:00) Canada/Mountain (Mountain Standard Time)',
            self::MEXICO_BAJASUR => '(GMT-7:00) Mexico/BajaSur (Mountain Standard Time)',
            self::AMERICA_BELIZE => '(GMT-6:00) America/Belize (Central Standard Time)',
            self::AMERICA_CANCUN => '(GMT-6:00) America/Cancun (Central Standard Time)',
            self::AMERICA_CHICAGO => '(GMT-6:00) America/Chicago (Central Standard Time)',
            self::AMERICA_COSTA_RICA => '(GMT-6:00) America/Costa_Rica (Central Standard Time)',
            self::AMERICA_EL_SALVADOR => '(GMT-6:00) America/El_Salvador (Central Standard Time)',
            self::AMERICA_GUATEMALA => '(GMT-6:00) America/Guatemala (Central Standard Time)',
            self::AMERICA_KNOX_IN => '(GMT-6:00) America/Knox_IN (Central Standard Time)',
            self::AMERICA_MANAGUA => '(GMT-6:00) America/Managua (Central Standard Time)',
            self::AMERICA_MENOMINEE => '(GMT-6:00) America/Menominee (Central Standard Time)',
            self::AMERICA_MERIDA => '(GMT-6:00) America/Merida (Central Standard Time)',
            self::AMERICA_MEXICO_CITY => '(GMT-6:00) America/Mexico_City (Central Standard Time)',
            self::AMERICA_MONTERREY => '(GMT-6:00) America/Monterrey (Central Standard Time)',
            self::AMERICA_RAINY_RIVER => '(GMT-6:00) America/Rainy_River (Central Standard Time)',
            self::AMERICA_RANKIN_INLET => '(GMT-6:00) America/Rankin_Inlet (Central Standard Time)',
            self::AMERICA_REGINA => '(GMT-6:00) America/Regina (Central Standard Time)',
            self::AMERICA_SWIFT_CURRENT => '(GMT-6:00) America/Swift_Current (Central Standard Time)',
            self::AMERICA_TEGUCIGALPA => '(GMT-6:00) America/Tegucigalpa (Central Standard Time)',
            self::AMERICA_WINNIPEG => '(GMT-6:00) America/Winnipeg (Central Standard Time)',
            self::CANADA_CENTRAL => '(GMT-6:00) Canada/Central (Central Standard Time)',
            self::CANADA_EAST_SASKATCHEWAN => '(GMT-6:00) Canada/East-Saskatchewan (Central Standard Time)',
            self::CANADA_SASKATCHEWAN => '(GMT-6:00) Canada/Saskatchewan (Central Standard Time)',
            self::CHILE_EASTERISLAND => '(GMT-6:00) Chile/EasterIsland (Easter Is. Time)',
            self::MEXICO_GENERAL => '(GMT-6:00) Mexico/General (Central Standard Time)',
            self::AMERICA_ATIKOKAN => '(GMT-5:00) America/Atikokan (Eastern Standard Time)',
            self::AMERICA_BOGOTA => '(GMT-5:00) America/Bogota (Colombia Time)',
            self::AMERICA_CAYMAN => '(GMT-5:00) America/Cayman (Eastern Standard Time)',
            self::AMERICA_CORAL_HARBOUR => '(GMT-5:00) America/Coral_Harbour (Eastern Standard Time)',
            self::AMERICA_DETROIT => '(GMT-5:00) America/Detroit (Eastern Standard Time)',
            self::AMERICA_FORT_WAYNE => '(GMT-5:00) America/Fort_Wayne (Eastern Standard Time)',
            self::AMERICA_GRAND_TURK => '(GMT-5:00) America/Grand_Turk (Eastern Standard Time)',
            self::AMERICA_GUAYAQUIL => '(GMT-5:00) America/Guayaquil (Ecuador Time)',
            self::AMERICA_HAVANA => '(GMT-5:00) America/Havana (Cuba Standard Time)',
            self::AMERICA_INDIANAPOLIS => '(GMT-5:00) America/Indianapolis (Eastern Standard Time)',
            self::AMERICA_IQALUIT => '(GMT-5:00) America/Iqaluit (Eastern Standard Time)',
            self::AMERICA_JAMAICA => '(GMT-5:00) America/Jamaica (Eastern Standard Time)',
            self::AMERICA_LIMA => '(GMT-5:00) America/Lima (Peru Time)',
            self::AMERICA_LOUISVILLE => '(GMT-5:00) America/Louisville (Eastern Standard Time)',
            self::AMERICA_MONTREAL => '(GMT-5:00) America/Montreal (Eastern Standard Time)',
            self::AMERICA_NASSAU => '(GMT-5:00) America/Nassau (Eastern Standard Time)',
            self::AMERICA_NEW_YORK => '(GMT-5:00) America/New_York (Eastern Standard Time)',
            self::AMERICA_NIPIGON => '(GMT-5:00) America/Nipigon (Eastern Standard Time)',
            self::AMERICA_PANAMA => '(GMT-5:00) America/Panama (Eastern Standard Time)',
            self::AMERICA_PANGNIRTUNG => '(GMT-5:00) America/Pangnirtung (Eastern Standard Time)',
            self::AMERICA_PORT_AU_PRINCE => '(GMT-5:00) America/Port-au-Prince (Eastern Standard Time)',
            self::AMERICA_RESOLUTE => '(GMT-5:00) America/Resolute (Eastern Standard Time)',
            self::AMERICA_THUNDER_BAY => '(GMT-5:00) America/Thunder_Bay (Eastern Standard Time)',
            self::AMERICA_TORONTO => '(GMT-5:00) America/Toronto (Eastern Standard Time)',
            self::CANADA_EASTERN => '(GMT-5:00) Canada/Eastern (Eastern Standard Time)',
            self::AMERICA_CARACAS => '(GMT-4:-30) America/Caracas (Venezuela Time)',
            self::AMERICA_ANGUILLA => '(GMT-4:00) America/Anguilla (Atlantic Standard Time)',
            self::AMERICA_ANTIGUA => '(GMT-4:00) America/Antigua (Atlantic Standard Time)',
            self::AMERICA_ARUBA => '(GMT-4:00) America/Aruba (Atlantic Standard Time)',
            self::AMERICA_ASUNCION => '(GMT-4:00) America/Asuncion (Paraguay Time)',
            self::AMERICA_BARBADOS => '(GMT-4:00) America/Barbados (Atlantic Standard Time)',
            self::AMERICA_BLANC_SABLON => '(GMT-4:00) America/Blanc-Sablon (Atlantic Standard Time)',
            self::AMERICA_BOA_VISTA => '(GMT-4:00) America/Boa_Vista (Amazon Time)',
            self::AMERICA_CAMPO_GRANDE => '(GMT-4:00) America/Campo_Grande (Amazon Time)',
            self::AMERICA_CUIABA => '(GMT-4:00) America/Cuiaba (Amazon Time)',
            self::AMERICA_CURACAO => '(GMT-4:00) America/Curacao (Atlantic Standard Time)',
            self::AMERICA_DOMINICA => '(GMT-4:00) America/Dominica (Atlantic Standard Time)',
            self::AMERICA_EIRUNEPE => '(GMT-4:00) America/Eirunepe (Acre Time)',
            self::AMERICA_GLACE_BAY => '(GMT-4:00) America/Glace_Bay (Atlantic Standard Time)',
            self::AMERICA_GOOSE_BAY => '(GMT-4:00) America/Goose_Bay (Atlantic Standard Time)',
            self::AMERICA_GRENADA => '(GMT-4:00) America/Grenada (Atlantic Standard Time)',
            self::AMERICA_GUADELOUPE => '(GMT-4:00) America/Guadeloupe (Atlantic Standard Time)',
            self::AMERICA_GUYANA => '(GMT-4:00) America/Guyana (Guyana Time)',
            self::AMERICA_HALIFAX => '(GMT-4:00) America/Halifax (Atlantic Standard Time)',
            self::AMERICA_LA_PAZ => '(GMT-4:00) America/La_Paz (Bolivia Time)',
            self::AMERICA_MANAUS => '(GMT-4:00) America/Manaus (Amazon Time)',
            self::AMERICA_MARIGOT => '(GMT-4:00) America/Marigot (Atlantic Standard Time)',
            self::AMERICA_MARTINIQUE => '(GMT-4:00) America/Martinique (Atlantic Standard Time)',
            self::AMERICA_MONCTON => '(GMT-4:00) America/Moncton (Atlantic Standard Time)',
            self::AMERICA_MONTSERRAT => '(GMT-4:00) America/Montserrat (Atlantic Standard Time)',
            self::AMERICA_PORT_OF_SPAIN => '(GMT-4:00) America/Port_of_Spain (Atlantic Standard Time)',
            self::AMERICA_PORTO_ACRE => '(GMT-4:00) America/Porto_Acre (Acre Time)',
            self::AMERICA_PORTO_VELHO => '(GMT-4:00) America/Porto_Velho (Amazon Time)',
            self::AMERICA_PUERTO_RICO => '(GMT-4:00) America/Puerto_Rico (Atlantic Standard Time)',
            self::AMERICA_RIO_BRANCO => '(GMT-4:00) America/Rio_Branco (Acre Time)',
            self::AMERICA_SANTIAGO => '(GMT-4:00) America/Santiago (Chile Standard Time)',
            self::AMERICA_SANTO_DOMINGO => '(GMT-4:00) America/Santo_Domingo (Dominican Republic Time)',
            self::AMERICA_ST_BARTHELEMY => '(GMT-4:00) America/St_Barthelemy (Atlantic Standard Time)',
            self::AMERICA_ST_KITTS => '(GMT-4:00) America/St_Kitts (Atlantic Standard Time)',
            self::AMERICA_ST_LUCIA => '(GMT-4:00) America/St_Lucia (Atlantic Standard Time)',
            self::AMERICA_ST_THOMAS => '(GMT-4:00) America/St_Thomas (Atlantic Standard Time)',
            self::AMERICA_ST_VINCENT => '(GMT-4:00) America/St_Vincent (Atlantic Standard Time)',
            self::AMERICA_THULE => '(GMT-4:00) America/Thule (Atlantic Standard Time)',
            self::AMERICA_TORTOLA => '(GMT-4:00) America/Tortola (Atlantic Standard Time)',
            self::AMERICA_VIRGIN => '(GMT-4:00) America/Virgin (Atlantic Standard Time)',
            self::ANTARCTICA_PALMER => '(GMT-4:00) Antarctica/Palmer (Chile Time)',
            self::ATLANTIC_BERMUDA => '(GMT-4:00) Atlantic/Bermuda (Atlantic Standard Time)',
            self::ATLANTIC_STANLEY => '(GMT-4:00) Atlantic/Stanley (Falkland Is. Time)',
            self::BRAZIL_ACRE => '(GMT-4:00) Brazil/Acre (Amazon Time)',
            self::BRAZIL_WEST => '(GMT-4:00) Brazil/West (Amazon Time)',
            self::CANADA_ATLANTIC => '(GMT-4:00) Canada/Atlantic (Atlantic Standard Time)',
            self::CHILE_CONTINENTAL => '(GMT-4:00) Chile/Continental (Chile Time)',
            self::AMERICA_ST_JOHNS => '(GMT-3:30) America/St_Johns (Newfoundland Standard Time)',
            self::CANADA_NEWFOUNDLAND => '(GMT-3:30) Canada/Newfoundland (Newfoundland Standard Time)',
            self::AMERICA_ARAGUAINA => '(GMT-3:00) America/Araguaina (Brasilia Time)',
            self::AMERICA_BAHIA => '(GMT-3:00) America/Bahia (Brasilia Time)',
            self::AMERICA_BELEM => '(GMT-3:00) America/Belem (Brasilia Time)',
            self::AMERICA_BUENOS_AIRES => '(GMT-3:00) America/Buenos_Aires (Argentine Time)',
            self::AMERICA_CATAMARCA => '(GMT-3:00) America/Catamarca (Argentine Time)',
            self::AMERICA_CAYENNE => '(GMT-3:00) America/Cayenne (French Guiana Time)',
            self::AMERICA_CORDOBA => '(GMT-3:00) America/Cordoba (Argentine Time)',
            self::AMERICA_FORTALEZA => '(GMT-3:00) America/Fortaleza (Brasilia Time)',
            self::AMERICA_GODTHAB => '(GMT-3:00) America/Godthab (Western Greenland Time)',
            self::AMERICA_JUJUY => '(GMT-3:00) America/Jujuy (Argentine Time)',
            self::AMERICA_MACEIO => '(GMT-3:00) America/Maceio (Brasilia Time)',
            self::AMERICA_MENDOZA => '(GMT-3:00) America/Mendoza (Argentine Time)',
            self::AMERICA_MIQUELON => '(GMT-3:00) America/Miquelon (Pierre & Miquelon Standard Time)',
            self::AMERICA_MONTEVIDEO => '(GMT-3:00) America/Montevideo (Uruguay Time)',
            self::AMERICA_PARAMARIBO => '(GMT-3:00) America/Paramaribo (Suriname Time)',
            self::AMERICA_RECIFE => '(GMT-3:00) America/Recife (Brasilia Time)',
            self::AMERICA_ROSARIO => '(GMT-3:00) America/Rosario (Argentine Time)',
            self::AMERICA_SANTAREM => '(GMT-3:00) America/Santarem (Brasilia Time)',
            self::AMERICA_SAO_PAULO => '(GMT-3:00) America/Sao_Paulo (Brasilia Time)',
            self::ANTARCTICA_ROTHERA => '(GMT-3:00) Antarctica/Rothera (Rothera Time)',
            self::BRAZIL_EAST => '(GMT-3:00) Brazil/East (Brasilia Time)',
            self::AMERICA_NORONHA => '(GMT-2:00) America/Noronha (Fernando de Noronha Time)',
            self::ATLANTIC_SOUTH_GEORGIA => '(GMT-2:00) Atlantic/South_Georgia (South Georgia Standard Time)',
            self::BRAZIL_DENORONHA => '(GMT-2:00) Brazil/DeNoronha (Fernando de Noronha Time)',
            self::AMERICA_SCORESBYSUND => '(GMT-1:00) America/Scoresbysund (Eastern Greenland Time)',
            self::ATLANTIC_AZORES => '(GMT-1:00) Atlantic/Azores (Azores Time)',
            self::ATLANTIC_CAPE_VERDE => '(GMT-1:00) Atlantic/Cape_Verde (Cape Verde Time)',
            self::AFRICA_ABIDJAN => '(GMT+0:00) Africa/Abidjan (Greenwich Mean Time)',
            self::AFRICA_ACCRA => '(GMT+0:00) Africa/Accra (Ghana Mean Time)',
            self::AFRICA_BAMAKO => '(GMT+0:00) Africa/Bamako (Greenwich Mean Time)',
            self::AFRICA_BANJUL => '(GMT+0:00) Africa/Banjul (Greenwich Mean Time)',
            self::AFRICA_BISSAU => '(GMT+0:00) Africa/Bissau (Greenwich Mean Time)',
            self::AFRICA_CASABLANCA => '(GMT+0:00) Africa/Casablanca (Western European Time)',
            self::AFRICA_CONAKRY => '(GMT+0:00) Africa/Conakry (Greenwich Mean Time)',
            self::AFRICA_DAKAR => '(GMT+0:00) Africa/Dakar (Greenwich Mean Time)',
            self::AFRICA_EL_AAIUN => '(GMT+0:00) Africa/El_Aaiun (Western European Time)',
            self::AFRICA_FREETOWN => '(GMT+0:00) Africa/Freetown (Greenwich Mean Time)',
            self::AFRICA_LOME => '(GMT+0:00) Africa/Lome (Greenwich Mean Time)',
            self::AFRICA_MONROVIA => '(GMT+0:00) Africa/Monrovia (Greenwich Mean Time)',
            self::AFRICA_NOUAKCHOTT => '(GMT+0:00) Africa/Nouakchott (Greenwich Mean Time)',
            self::AFRICA_OUAGADOUGOU => '(GMT+0:00) Africa/Ouagadougou (Greenwich Mean Time)',
            self::AFRICA_SAO_TOME => '(GMT+0:00) Africa/Sao_Tome (Greenwich Mean Time)',
            self::AFRICA_TIMBUKTU => '(GMT+0:00) Africa/Timbuktu (Greenwich Mean Time)',
            self::AMERICA_DANMARKSHAVN => '(GMT+0:00) America/Danmarkshavn (Greenwich Mean Time)',
            self::ATLANTIC_CANARY => '(GMT+0:00) Atlantic/Canary (Western European Time)',
            self::ATLANTIC_FAEROE => '(GMT+0:00) Atlantic/Faeroe (Western European Time)',
            self::ATLANTIC_FAROE => '(GMT+0:00) Atlantic/Faroe (Western European Time)',
            self::ATLANTIC_MADEIRA => '(GMT+0:00) Atlantic/Madeira (Western European Time)',
            self::ATLANTIC_REYKJAVIK => '(GMT+0:00) Atlantic/Reykjavik (Greenwich Mean Time)',
            self::ATLANTIC_ST_HELENA => '(GMT+0:00) Atlantic/St_Helena (Greenwich Mean Time)',
            self::EUROPE_BELFAST => '(GMT+0:00) Europe/Belfast (Greenwich Mean Time)',
            self::EUROPE_DUBLIN => '(GMT+0:00) Europe/Dublin (Greenwich Mean Time)',
            self::EUROPE_GUERNSEY => '(GMT+0:00) Europe/Guernsey (Greenwich Mean Time)',
            self::EUROPE_ISLE_OF_MAN => '(GMT+0:00) Europe/Isle_of_Man (Greenwich Mean Time)',
            self::EUROPE_JERSEY => '(GMT+0:00) Europe/Jersey (Greenwich Mean Time)',
            self::EUROPE_LISBON => '(GMT+0:00) Europe/Lisbon (Western European Time)',
            self::EUROPE_LONDON => '(GMT+0:00) Europe/London (Greenwich Mean Time)',
            self::AFRICA_ALGIERS => '(GMT+1:00) Africa/Algiers (Central European Time)',
            self::AFRICA_BANGUI => '(GMT+1:00) Africa/Bangui (Western African Time)',
            self::AFRICA_BRAZZAVILLE => '(GMT+1:00) Africa/Brazzaville (Western African Time)',
            self::AFRICA_CEUTA => '(GMT+1:00) Africa/Ceuta (Central European Time)',
            self::AFRICA_DOUALA => '(GMT+1:00) Africa/Douala (Western African Time)',
            self::AFRICA_KINSHASA => '(GMT+1:00) Africa/Kinshasa (Western African Time)',
            self::AFRICA_LAGOS => '(GMT+1:00) Africa/Lagos (Western African Time)',
            self::AFRICA_LIBREVILLE => '(GMT+1:00) Africa/Libreville (Western African Time)',
            self::AFRICA_LUANDA => '(GMT+1:00) Africa/Luanda (Western African Time)',
            self::AFRICA_MALABO => '(GMT+1:00) Africa/Malabo (Western African Time)',
            self::AFRICA_NDJAMENA => '(GMT+1:00) Africa/Ndjamena (Western African Time)',
            self::AFRICA_NIAMEY => '(GMT+1:00) Africa/Niamey (Western African Time)',
            self::AFRICA_PORTO_NOVO => '(GMT+1:00) Africa/Porto-Novo (Western African Time)',
            self::AFRICA_TUNIS => '(GMT+1:00) Africa/Tunis (Central European Time)',
            self::AFRICA_WINDHOEK => '(GMT+1:00) Africa/Windhoek (Western African Time)',
            self::ARCTIC_LONGYEARBYEN => '(GMT+1:00) Arctic/Longyearbyen (Central European Time)',
            self::ATLANTIC_JAN_MAYEN => '(GMT+1:00) Atlantic/Jan_Mayen (Central European Time)',
            self::EUROPE_AMSTERDAM => '(GMT+1:00) Europe/Amsterdam (Central European Time)',
            self::EUROPE_ANDORRA => '(GMT+1:00) Europe/Andorra (Central European Time)',
            self::EUROPE_BELGRADE => '(GMT+1:00) Europe/Belgrade (Central European Time)',
            self::EUROPE_BERLIN => '(GMT+1:00) Europe/Berlin (Central European Time)',
            self::EUROPE_BRATISLAVA => '(GMT+1:00) Europe/Bratislava (Central European Time)',
            self::EUROPE_BRUSSELS => '(GMT+1:00) Europe/Brussels (Central European Time)',
            self::EUROPE_BUDAPEST => '(GMT+1:00) Europe/Budapest (Central European Time)',
            self::EUROPE_COPENHAGEN => '(GMT+1:00) Europe/Copenhagen (Central European Time)',
            self::EUROPE_GIBRALTAR => '(GMT+1:00) Europe/Gibraltar (Central European Time)',
            self::EUROPE_LJUBLJANA => '(GMT+1:00) Europe/Ljubljana (Central European Time)',
            self::EUROPE_LUXEMBOURG => '(GMT+1:00) Europe/Luxembourg (Central European Time)',
            self::EUROPE_MADRID => '(GMT+1:00) Europe/Madrid (Central European Time)',
            self::EUROPE_MALTA => '(GMT+1:00) Europe/Malta (Central European Time)',
            self::EUROPE_MONACO => '(GMT+1:00) Europe/Monaco (Central European Time)',
            self::EUROPE_OSLO => '(GMT+1:00) Europe/Oslo (Central European Time)',
            self::EUROPE_PARIS => '(GMT+1:00) Europe/Paris (Central European Time)',
            self::EUROPE_PODGORICA => '(GMT+1:00) Europe/Podgorica (Central European Time)',
            self::EUROPE_PRAGUE => '(GMT+1:00) Europe/Prague (Central European Time)',
            self::EUROPE_ROME => '(GMT+1:00) Europe/Rome (Central European Time)',
            self::EUROPE_SAN_MARINO => '(GMT+1:00) Europe/San_Marino (Central European Time)',
            self::EUROPE_SARAJEVO => '(GMT+1:00) Europe/Sarajevo (Central European Time)',
            self::EUROPE_SKOPJE => '(GMT+1:00) Europe/Skopje (Central European Time)',
            self::EUROPE_STOCKHOLM => '(GMT+1:00) Europe/Stockholm (Central European Time)',
            self::EUROPE_TIRANE => '(GMT+1:00) Europe/Tirane (Central European Time)',
            self::EUROPE_VADUZ => '(GMT+1:00) Europe/Vaduz (Central European Time)',
            self::EUROPE_VATICAN => '(GMT+1:00) Europe/Vatican (Central European Time)',
            self::EUROPE_VIENNA => '(GMT+1:00) Europe/Vienna (Central European Time)',
            self::EUROPE_WARSAW => '(GMT+1:00) Europe/Warsaw (Central European Time)',
            self::EUROPE_ZAGREB => '(GMT+1:00) Europe/Zagreb (Central European Time)',
            self::EUROPE_ZURICH => '(GMT+1:00) Europe/Zurich (Central European Time)',
            self::AFRICA_BLANTYRE => '(GMT+2:00) Africa/Blantyre (Central African Time)',
            self::AFRICA_BUJUMBURA => '(GMT+2:00) Africa/Bujumbura (Central African Time)',
            self::AFRICA_CAIRO => '(GMT+2:00) Africa/Cairo (Eastern European Time)',
            self::AFRICA_GABORONE => '(GMT+2:00) Africa/Gaborone (Central African Time)',
            self::AFRICA_HARARE => '(GMT+2:00) Africa/Harare (Central African Time)',
            self::AFRICA_JOHANNESBURG => '(GMT+2:00) Africa/Johannesburg (South Africa Standard Time)',
            self::AFRICA_KIGALI => '(GMT+2:00) Africa/Kigali (Central African Time)',
            self::AFRICA_LUBUMBASHI => '(GMT+2:00) Africa/Lubumbashi (Central African Time)',
            self::AFRICA_LUSAKA => '(GMT+2:00) Africa/Lusaka (Central African Time)',
            self::AFRICA_MAPUTO => '(GMT+2:00) Africa/Maputo (Central African Time)',
            self::AFRICA_MASERU => '(GMT+2:00) Africa/Maseru (South Africa Standard Time)',
            self::AFRICA_MBABANE => '(GMT+2:00) Africa/Mbabane (South Africa Standard Time)',
            self::AFRICA_TRIPOLI => '(GMT+2:00) Africa/Tripoli (Eastern European Time)',
            self::ASIA_AMMAN => '(GMT+2:00) Asia/Amman (Eastern European Time)',
            self::ASIA_BEIRUT => '(GMT+2:00) Asia/Beirut (Eastern European Time)',
            self::ASIA_DAMASCUS => '(GMT+2:00) Asia/Damascus (Eastern European Time)',
            self::ASIA_GAZA => '(GMT+2:00) Asia/Gaza (Eastern European Time)',
            self::ASIA_ISTANBUL => '(GMT+2:00) Asia/Istanbul (Eastern European Time)',
            self::ASIA_JERUSALEM => '(GMT+2:00) Asia/Jerusalem (Israel Standard Time)',
            self::ASIA_NICOSIA => '(GMT+2:00) Asia/Nicosia (Eastern European Time)',
            self::ASIA_TEL_AVIV => '(GMT+2:00) Asia/Tel_Aviv (Israel Standard Time)',
            self::EUROPE_ATHENS => '(GMT+2:00) Europe/Athens (Eastern European Time)',
            self::EUROPE_BUCHAREST => '(GMT+2:00) Europe/Bucharest (Eastern European Time)',
            self::EUROPE_CHISINAU => '(GMT+2:00) Europe/Chisinau (Eastern European Time)',
            self::EUROPE_HELSINKI => '(GMT+2:00) Europe/Helsinki (Eastern European Time)',
            self::EUROPE_KALININGRAD => '(GMT+2:00) Europe/Kaliningrad (Eastern European Time)',
            self::EUROPE_KIEV => '(GMT+2:00) Europe/Kiev (Eastern European Time)',
            self::EUROPE_MARIEMAN => '(GMT+2:00) Europe/Mariehamn (Eastern European Time)',
            self::EUROPE_MINSK => '(GMT+2:00) Europe/Minsk (Eastern European Time)',
            self::EUROPE_NICOSIA => '(GMT+2:00) Europe/Nicosia (Eastern European Time)',
            self::EUROPE_RIGA => '(GMT+2:00) Europe/Riga (Eastern European Time)',
            self::EUROPE_SIMFEROPOL => '(GMT+2:00) Europe/Simferopol (Eastern European Time)',
            self::EUROPE_SOFIA => '(GMT+2:00) Europe/Sofia (Eastern European Time)',
            self::EUROPE_TALLINN => '(GMT+2:00) Europe/Tallinn (Eastern European Time)',
            self::EUROPE_TIRASPOL => '(GMT+2:00) Europe/Tiraspol (Eastern European Time)',
            self::EUROPE_UZHGOROD => '(GMT+2:00) Europe/Uzhgorod (Eastern European Time)',
            self::EUROPE_VILNIUS => '(GMT+2:00) Europe/Vilnius (Eastern European Time)',
            self::EUROPE_ZAPOROZHYE => '(GMT+2:00) Europe/Zaporozhye (Eastern European Time)',
            self::AFRICA_ADDIS_ABABA => '(GMT+3:00) Africa/Addis_Ababa (Eastern African Time)',
            self::AFRICA_ASMARA => '(GMT+3:00) Africa/Asmara (Eastern African Time)',
            self::AFRICA_ASMERA => '(GMT+3:00) Africa/Asmera (Eastern African Time)',
            self::AFRICA_DAR_ES_SALAAM => '(GMT+3:00) Africa/Dar_es_Salaam (Eastern African Time)',
            self::AFRICA_DJIBOUTI => '(GMT+3:00) Africa/Djibouti (Eastern African Time)',
            self::AFRICA_KAMPALA => '(GMT+3:00) Africa/Kampala (Eastern African Time)',
            self::AFRICA_KHARTOUM => '(GMT+3:00) Africa/Khartoum (Eastern African Time)',
            self::AFRICA_MOGADISHU => '(GMT+3:00) Africa/Mogadishu (Eastern African Time)',
            self::AFRICA_NAIROBI => '(GMT+3:00) Africa/Nairobi (Eastern African Time)',
            self::ANTARCTICA_SYOWA => '(GMT+3:00) Antarctica/Syowa (Syowa Time)',
            self::ASIA_ADEN => '(GMT+3:00) Asia/Aden (Arabia Standard Time)',
            self::ASIA_BAGHDAD => '(GMT+3:00) Asia/Baghdad (Arabia Standard Time)',
            self::ASIA_BAHRAIN => '(GMT+3:00) Asia/Bahrain (Arabia Standard Time)',
            self::ASIA_KUWAIT => '(GMT+3:00) Asia/Kuwait (Arabia Standard Time)',
            self::ASIA_QATAR => '(GMT+3:00) Asia/Qatar (Arabia Standard Time)',
            self::EUROPE_MOSCOW => '(GMT+3:00) Europe/Moscow (Moscow Standard Time)',
            self::EUROPE_VOLGOGRAD => '(GMT+3:00) Europe/Volgograd (Volgograd Time)',
            self::INDIAN_ANTANANARIVO => '(GMT+3:00) Indian/Antananarivo (Eastern African Time)',
            self::INDIAN_COMORO => '(GMT+3:00) Indian/Comoro (Eastern African Time)',
            self::INDIAN_MAYOTTE => '(GMT+3:00) Indian/Mayotte (Eastern African Time)',
            self::ASIA_TEHRAN => '(GMT+3:30) Asia/Tehran (Iran Standard Time)',
            self::ASIA_BAKU => '(GMT+4:00) Asia/Baku (Azerbaijan Time)',
            self::ASIA_DUBAI => '(GMT+4:00) Asia/Dubai (Gulf Standard Time)',
            self::ASIA_MUSCAT => '(GMT+4:00) Asia/Muscat (Gulf Standard Time)',
            self::ASIA_TBILISI => '(GMT+4:00) Asia/Tbilisi (Georgia Time)',
            self::ASIA_YEREVAN => '(GMT+4:00) Asia/Yerevan (Armenia Time)',
            self::EUROPE_SAMARA => '(GMT+4:00) Europe/Samara (Samara Time)',
            self::INDIAN_MAHE => '(GMT+4:00) Indian/Mahe (Seychelles Time)',
            self::INDIAN_MAURITIUS => '(GMT+4:00) Indian/Mauritius (Mauritius Time)',
            self::INDIAN_REUNION => '(GMT+4:00) Indian/Reunion (Reunion Time)',
            self::ASIA_KABUL => '(GMT+4:30) Asia/Kabul (Afghanistan Time)',
            self::ASIA_AQTAU => '(GMT+5:00) Asia/Aqtau (Aqtau Time)',
            self::ASIA_AQTOBE => '(GMT+5:00) Asia/Aqtobe (Aqtobe Time)',
            self::ASIA_ASHGABAT => '(GMT+5:00) Asia/Ashgabat (Turkmenistan Time)',
            self::ASIA_ASHKHABAD => '(GMT+5:00) Asia/Ashkhabad (Turkmenistan Time)',
            self::ASIA_DUSHANBE => '(GMT+5:00) Asia/Dushanbe (Tajikistan Time)',
            self::ASIA_KARACHI => '(GMT+5:00) Asia/Karachi (Pakistan Time)',
            self::ASIA_ORAL => '(GMT+5:00) Asia/Oral (Oral Time)',
            self::ASIA_SAMARKAND => '(GMT+5:00) Asia/Samarkand (Uzbekistan Time)',
            self::ASIA_TASHKENT => '(GMT+5:00) Asia/Tashkent (Uzbekistan Time)',
            self::ASIA_YEKATERINBURG => '(GMT+5:00) Asia/Yekaterinburg (Yekaterinburg Time)',
            self::INDIAN_KERGUELEN => '(GMT+5:00) Indian/Kerguelen (French Southern & Antarctic Lands Time)',
            self::INDIAN_MALDIVES => '(GMT+5:00) Indian/Maldives (Maldives Time)',
            self::ASIA_CALCUTTA => '(GMT+5:30) Asia/Calcutta (India Standard Time)',
            self::ASIA_COLOMBO => '(GMT+5:30) Asia/Colombo (India Standard Time)',
            self::ASIA_KOLKATA => '(GMT+5:30) Asia/Kolkata (India Standard Time)',
            self::ASIA_KATMANDU => '(GMT+5:45) Asia/Katmandu (Nepal Time)',
            self::ANTARCTICA_MAWSON => '(GMT+6:00) Antarctica/Mawson (Mawson Time)',
            self::ANTARCTICA_VOSTOK => '(GMT+6:00) Antarctica/Vostok (Vostok Time)',
            self::ASIA_ALMATY => '(GMT+6:00) Asia/Almaty (Alma-Ata Time)',
            self::ASIA_BISHKEK => '(GMT+6:00) Asia/Bishkek (Kirgizstan Time)',
            self::ASIA_DACCA => '(GMT+6:00) Asia/Dacca (Bangladesh Time)',
            self::ASIA_DHAKA => '(GMT+6:00) Asia/Dhaka (Bangladesh Time)',
            self::ASIA_NOVOSIBIRSK => '(GMT+6:00) Asia/Novosibirsk (Novosibirsk Time)',
            self::ASIA_OMSK => '(GMT+6:00) Asia/Omsk (Omsk Time)',
            self::ASIA_QYZYLORDA => '(GMT+6:00) Asia/Qyzylorda (Qyzylorda Time)',
            self::ASIA_THIMBU => '(GMT+6:00) Asia/Thimbu (Bhutan Time)',
            self::ASIA_THIMPHU => '(GMT+6:00) Asia/Thimphu (Bhutan Time)',
            self::INDIAN_CHAGOS => '(GMT+6:00) Indian/Chagos (Indian Ocean Territory Time)',
            self::ASIA_RANGOON => '(GMT+6:30) Asia/Rangoon (Myanmar Time)',
            self::INDIAN_COCOS => '(GMT+6:30) Indian/Cocos (Cocos Islands Time)',
            self::ANTARCTICA_DAVIS => '(GMT+7:00) Antarctica/Davis (Davis Time)',
            self::ASIA_BANGKOK => '(GMT+7:00) Asia/Bangkok (Indochina Time)',
            self::ASIA_HO_CHI_MINH => '(GMT+7:00) Asia/Ho_Chi_Minh (Indochina Time)',
            self::ASIA_HOVD => '(GMT+7:00) Asia/Hovd (Hovd Time)',
            self::ASIA_JAKARTA => '(GMT+7:00) Asia/Jakarta (West Indonesia Time)',
            self::ASIA_KRASNOYARSK => '(GMT+7:00) Asia/Krasnoyarsk (Krasnoyarsk Time)',
            self::ASIA_PHNOM_PENH => '(GMT+7:00) Asia/Phnom_Penh (Indochina Time)',
            self::ASIA_PONTIANAK => '(GMT+7:00) Asia/Pontianak (West Indonesia Time)',
            self::ASIA_SAIGON => '(GMT+7:00) Asia/Saigon (Indochina Time)',
            self::ASIA_VIENTIANE => '(GMT+7:00) Asia/Vientiane (Indochina Time)',
            self::INDIAN_CHRISTMAS => '(GMT+7:00) Indian/Christmas (Christmas Island Time)',
            self::ANTARCTICA_CASEY => '(GMT+8:00) Antarctica/Casey (Western Standard Time (Australia))',
            self::ASIA_BRUNEI => '(GMT+8:00) Asia/Brunei (Brunei Time)',
            self::ASIA_CHOIBALSAN => '(GMT+8:00) Asia/Choibalsan (Choibalsan Time)',
            self::ASIA_CHONGQING => '(GMT+8:00) Asia/Chongqing (China Standard Time)',
            self::ASIA_CHUNGKING => '(GMT+8:00) Asia/Chungking (China Standard Time)',
            self::ASIA_HARBIN => '(GMT+8:00) Asia/Harbin (China Standard Time)',
            self::ASIA_HONG_KONG => '(GMT+8:00) Asia/Hong_Kong (Hong Kong Time)',
            self::ASIA_IRKUTSK => '(GMT+8:00) Asia/Irkutsk (Irkutsk Time)',
            self::ASIA_KASHGAR => '(GMT+8:00) Asia/Kashgar (China Standard Time)',
            self::ASIA_KUALA_LUMPUR => '(GMT+8:00) Asia/Kuala_Lumpur (Malaysia Time)',
            self::ASIA_KUCHING => '(GMT+8:00) Asia/Kuching (Malaysia Time)',
            self::ASIA_MACAO => '(GMT+8:00) Asia/Macao (China Standard Time)',
            self::ASIA_MACAU => '(GMT+8:00) Asia/Macau (China Standard Time)',
            self::ASIA_MAKASSAR => '(GMT+8:00) Asia/Makassar (Central Indonesia Time)',
            self::ASIA_MANILA => '(GMT+8:00) Asia/Manila (Philippines Time)',
            self::ASIA_SHANGHAI => '(GMT+8:00) Asia/Shanghai (China Standard Time)',
            self::ASIA_SINGAPORE => '(GMT+8:00) Asia/Singapore (Singapore Time)',
            self::ASIA_TAIPEI => '(GMT+8:00) Asia/Taipei (China Standard Time)',
            self::ASIA_UJUNG_PANDANG => '(GMT+8:00) Asia/Ujung_Pandang (Central Indonesia Time)',
            self::ASIA_ULAANBAATAR => '(GMT+8:00) Asia/Ulaanbaatar (Ulaanbaatar Time)',
            self::ASIA_ULAN_BATOR => '(GMT+8:00) Asia/Ulan_Bator (Ulaanbaatar Time)',
            self::ASIA_URUMQI => '(GMT+8:00) Asia/Urumqi (China Standard Time)',
            self::AUSTRALIA_PERTH => '(GMT+8:00) Australia/Perth (Western Standard Time (Australia))',
            self::AUSTRALIA_WEST => '(GMT+8:00) Australia/West (Western Standard Time (Australia))',
            self::AUSTRALIA_EUCLA => '(GMT+8:45) Australia/Eucla (Central Western Standard Time (Australia))',
            self::ASIA_DILI => '(GMT+9:00) Asia/Dili (Timor-Leste Time)',
            self::ASIA_JAYAPURA => '(GMT+9:00) Asia/Jayapura (East Indonesia Time)',
            self::ASIA_PYONGYANG => '(GMT+9:00) Asia/Pyongyang (Korea Standard Time)',
            self::ASIA_SEOUL => '(GMT+9:00) Asia/Seoul (Korea Standard Time)',
            self::ASIA_TOKYO => '(GMT+9:00) Asia/Tokyo (Japan Standard Time)',
            self::ASIA_YAKUTSK => '(GMT+9:00) Asia/Yakutsk (Yakutsk Time)',
            self::AUSTRALIA_ADELAIDE => '(GMT+9:30) Australia/Adelaide (Central Standard Time (South Australia))',
            self::AUSTRALIA_BROKEN_HILL => '(GMT+9:30) Australia/Broken_Hill (Central Standard Time (South Australia/New South Wales))',
            self::AUSTRALIA_DARWIN => '(GMT+9:30) Australia/Darwin (Central Standard Time (Northern Territory))',
            self::AUSTRALIA_NORTH => '(GMT+9:30) Australia/North (Central Standard Time (Northern Territory))',
            self::AUSTRALIA_SOUTH => '(GMT+9:30) Australia/South (Central Standard Time (South Australia))',
            self::AUSTRALIA_YANCOWINNA => '(GMT+9:30) Australia/Yancowinna (Central Standard Time (South Australia/New South Wales))',
            self::ANTARCTICA_DUMONT_DURVILLE => '(GMT+10:00) Antarctica/DumontDUrville (Dumont-d\'Urville Time)',
            self::ASIA_SAKHALIN => '(GMT+10:00) Asia/Sakhalin (Sakhalin Time)',
            self::ASIA_VLADIVOSTOK => '(GMT+10:00) Asia/Vladivostok (Vladivostok Time)',
            self::AUSTRALIA_ACT => '(GMT+10:00) Australia/ACT (Eastern Standard Time (New South Wales))',
            self::AUSTRALIA_BRISBANE => '(GMT+10:00) Australia/Brisbane (Eastern Standard Time (Queensland))',
            self::AUSTRALIA_CANBERRA => '(GMT+10:00) Australia/Canberra (Eastern Standard Time (New South Wales))',
            self::AUSTRALIA_CURRIE => '(GMT+10:00) Australia/Currie (Eastern Standard Time (New South Wales))',
            self::AUSTRALIA_HOBART => '(GMT+10:00) Australia/Hobart (Eastern Standard Time (Tasmania))',
            self::AUSTRALIA_LINDEMAN => '(GMT+10:00) Australia/Lindeman (Eastern Standard Time (Queensland))',
            self::AUSTRALIA_MELBOURNE => '(GMT+10:00) Australia/Melbourne (Eastern Standard Time (Victoria))',
            self::AUSTRALIA_NSW => '(GMT+10:00) Australia/NSW (Eastern Standard Time (New South Wales))',
            self::AUSTRALIA_QUEENSLAND => '(GMT+10:00) Australia/Queensland (Eastern Standard Time (Queensland))',
            self::AUSTRALIA_SYDNEY => '(GMT+10:00) Australia/Sydney (Eastern Standard Time (New South Wales))',
            self::AUSTRALIA_TASMANIA => '(GMT+10:00) Australia/Tasmania (Eastern Standard Time (Tasmania))',
            self::AUSTRALIA_VICTORIA => '(GMT+10:00) Australia/Victoria (Eastern Standard Time (Victoria))',
            self::AUSTRALIA_LHI => '(GMT+10:30) Australia/LHI (Lord Howe Standard Time)',
            self::AUSTRALIA_LORD_HOWE => '(GMT+10:30) Australia/Lord_Howe (Lord Howe Standard Time)',
            self::ASIA_MAGADAN => '(GMT+11:00) Asia/Magadan (Magadan Time)',
            self::ANTARCTICA_MCMURDO => '(GMT+12:00) Antarctica/McMurdo (New Zealand Standard Time)',
            self::ANTARCTICA_SOUTH_POLE => '(GMT+12:00) Antarctica/South_Pole (New Zealand Standard Time)',
            self::ASIA_ANADYR => '(GMT+12:00) Asia/Anadyr (Anadyr Time)',
            self::ASIA_KAMCHATKA => '(GMT+12:00) Asia/Kamchatka (Petropavlovsk-Kamchatski Time)',
        };
    }
}
