<?php
require_once __DIR__ . '/filter.php';
/*
 ** This file defines the admin panel of photobooth. The admin panel definition is done in a JSON variable and structured as follows
 **
 ** Admin panel
 **     |- Section 1
 **     |  |- Parameter 1
 **     |  |- Parameter 2
 **     |  |- Setting A
 **     |  |- Setting B
 **     |
 **     |- Section 2
 **     |  |- Setting C
 **     |  |- Setting D
 **     |  |- Setting E
 **     |
 **     |- Section 3
 **     |  |- Parameter 1
 **     |  |- ...
 **     |
 **     |...
 **
 ** * Section descriptor
 **   - Always key / array pair
 **      * 'key': always starts with a character, consists of characters, numbers and underscore only
 **   - Admin panel sort order is defined by the order in this config file
 **   - The i18n tag for translation is identified by the actual section key
 **   - Parameter: Key / Value pairs are parameters which apply to how the section is displayed in the admin panel
 **     	* 'view' (optional): Accepted values are 'basic', 'advanced' or 'expert'. Defines in which admin panel view mode
 ** 	  	 	     the section is shown or not. Missing parameter defaults to 'expert'.
 ** 	* 'platform' (optional): Accepted values are 'all', 'linux', 'windows'. Defines whether the section is visible
 ** 	  	     		 by platform. Missing parameter defaults to 'all'
 **   - Settings: Key / Array pairs define a setting (see next)
 **
 ** * Settings descriptor
 **   - Is a key / array pair where the key string is distinct across the entire admin panel. Even with different sections, no
 **     duplicate setting keys are allowed across the file.
 **      * 'key': always starts with a character, consists of characters, numbers and underscore only
 **   - Admin panel sort order is defined by the order in this config file
 **   - The i18n tag for translation is identified by concatenation of  section key, ':', setting key. Tags for manual entries
 **     start with "manual:"
 **     Examples:
 **		"general:language"
 **		"user_interface:toggle_fs_button"
 **		"manual:print:use_print_result"
 **
 **   - Parameter: Can be key/value or key/array pairs. Sort order does not matter.
 **     	* 'view' (optional): Accepted values are 'basic', 'advanced' or 'expert'. Defines in which admin panel view mode
 ** 	  	 	     the section is shown or not. Missing parameter defaults to 'expert'.
 ** 	* 'name': Matches the name of the config variable or array
 ** 	* 'type': Values are 'input', 'range', 'color', 'hidden', 'checkbox', 'multi-select', 'select'. Defines the actual
 ** 	  	  input type in the admin panel for this setting.
 ** 	* 'value': Value is a reference to the actual PB config (i.e. 'value' => $config['auto_reload_on_error']) and pre-
 ** 	  	   populates the current config value into the admin panel
 ** 	* 'placeholder': Only for types 'input', 'range', 'color' to prepopulate / preset the admin panel setting entry
 ** 	  		 field / range selector. Often references the default config for this setting
 ** 			 (i.e 'placeholder' => $defaultConfig['time_to_live'])
 ** 	* 'option': Only for types 'select','multi-select'. Lists the options available in this setting (i.e.
 **   	                'options' => [
 **                 		  '360px' => 'XS',
 **                 		  '540px' => 'S',
 ** 				  ]
 ** 	* 'range_min', 'range_max', 'range_step': Only for type 'range'. Define the slider range and step when moved
 ** 	* 'unit': Only for type 'range'. Defines the unit of the slider and is used to identify the i18n tag for translation of the unit
 */

$configsetup = [
    'general' => [
        'view' => 'basic',
        'platform' => 'all',
        'language' => [
            'view' => 'basic',
            'type' => 'select',
            'name' => 'language',
            'placeholder' => $defaultConfig['language'],
            'options' => [
                'de' => 'DE',
                'el' => 'EL',
                'en' => 'EN',
                'es' => 'ES',
                'fr' => 'FR',
                'pl' => 'PL',
                'it' => 'IT',
            ],
            'value' => $config['language'],
        ],
        'adminpanel_view' => [
            'view' => 'basic',
            'type' => 'select',
            'name' => 'adminpanel_view',
            'placeholder' => $defaultConfig['adminpanel_view'],
            'options' => [
                'basic' => 'Basic View',
                'advanced' => 'Advanced View',
                'expert' => 'Expert View',
            ],
            'value' => $config['adminpanel_view'],
        ],
        'adminpanel_view_default' => [
            'view' => 'expert',
            'type' => 'hidden',
            'name' => 'adminpanel_view_default',
            'value' => $config['adminpanel_view_default'],
        ],
        'dev' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'dev',
            'value' => $config['dev'],
        ],
        'start_screen_title' => [
            'type' => 'input',
            'placeholder' => $defaultConfig['start_screen_title'],
            'name' => 'start_screen_title',
            'value' => htmlentities($config['start_screen_title']),
        ],
        'start_screen_subtitle' => [
            'type' => 'input',
            'placeholder' => $defaultConfig['start_screen_subtitle'],
            'name' => 'start_screen_subtitle',
            'value' => htmlentities($config['start_screen_subtitle']),
        ],
        'thumb_size' => [
            'view' => 'advanced',
            'type' => 'select',
            'name' => 'thumb_size',
            'placeholder' => $defaultConfig['thumb_size'],
            'options' => [
                '360px' => 'XS',
                '540px' => 'S',
                '900px' => 'M',
                '1080px' => 'L',
                '1260px' => 'XL',
            ],
            'value' => $config['thumb_size'],
        ],
        'show_error_messages' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'show_error_messages',
            'value' => $config['show_error_messages'],
        ],
        'auto_reload_on_error' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'auto_reload_on_error',
            'value' => $config['auto_reload_on_error'],
        ],
        'use_qr' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'use_qr',
            'value' => $config['use_qr'],
        ],
        'webserver_ip' => [
            'view' => 'advanced',
            'type' => 'input',
            'name' => 'webserver_ip',
            'placeholder' => '127.0.0.1',
            'value' => $config['webserver_ip'],
        ],
        'wifi_ssid' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'wifi_ssid',
            'placeholder' => 'Photobooth',
            'value' => htmlentities($config['wifi_ssid']),
        ],
        'use_download' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'use_download',
            'value' => $config['use_download'],
        ],
        'download_thumbs' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'download_thumbs',
            'value' => $config['download_thumbs'],
        ],
        'time_to_live' => [
            'view' => 'expert',
            'type' => 'range',
            'placeholder' => $defaultConfig['time_to_live'],
            'name' => 'time_to_live',
            'value' => $config['time_to_live'],
            'range_min' => 1000,
            'range_max' => 90000,
            'range_step' => 1000,
            'unit' => 'milliseconds',
        ],
        'image_preview_before_processing' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'image_preview_before_processing',
            'value' => $config['image_preview_before_processing'],
        ],
        'db_file' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['db_file'],
            'name' => 'db_file',
            'value' => $config['db_file'],
        ],
    ],
    'frontpage' => [
        'view' => 'basic',
        'show_fork' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'show_fork',
            'value' => $config['show_fork'],
        ],
        'is_event' => [
            'type' => 'checkbox',
            'name' => 'is_event',
            'value' => $config['is_event'],
        ],
        'textLeft' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => 'Name 1',
            'name' => 'event[textLeft]',
            'value' => htmlentities($config['event']['textLeft']),
        ],
        'symbol' => [
            'view' => 'basic',
            'type' => 'select',
            'name' => 'event[symbol]',
            'placeholder' => $defaultConfig['event']['symbol'],
            'options' => [
                'fa-camera' => 'Camera',
                'fa-camera-retro' => 'Camera Retro',
                'fa-birthday-cake' => 'Birthday Cake',
                'fa-gift' => 'Gift',
                'fa-tree' => 'Tree',
                'fa-snowflake-o' => 'Snowflake',
                'fa-heart-o' => 'Heart',
                'fa-heart' => 'Heart filled',
                'fa-heartbeat' => 'Heartbeat',
                'fa-apple' => 'Apple',
                'fa-anchor' => 'Anchor',
                'fa-glass' => 'Glass',
                'fa-gears' => 'Gears',
                'fa-users' => 'People',
            ],
            'value' => $config['event']['symbol'],
        ],
        'textRight' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => 'Name 2',
            'name' => 'event[textRight]',
            'value' => htmlentities($config['event']['textRight']),
        ],
        'force_buzzer' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'force_buzzer',
            'value' => $config['force_buzzer'],
        ],
    ],
    'pictures' => [
        'view' => 'basic',
        'platform' => 'all',
        'cntdwn_time' => [
            'view' => 'basic',
            'type' => 'range',
            'name' => 'cntdwn_time',
            'placeholder' => $defaultConfig['cntdwn_time'],
            'value' => $config['cntdwn_time'],
            'range_min' => 1,
            'range_max' => 10,
            'range_step' => 1,
            'unit' => 'seconds',
        ],
        'no_cheese' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'no_cheese',
            'value' => $config['no_cheese'],
        ],
        'cheese_time' => [
            'view' => 'advanced',
            'type' => 'range',
            'placeholder' => $defaultConfig['cheese_time'],
            'name' => 'cheese_time',
            'value' => $config['cheese_time'],
            'range_min' => 250,
            'range_max' => 10000,
            'range_step' => 250,
            'unit' => 'milliseconds',
        ],
        'pictureRotation' => [
            'view' => 'advanced',
            'type' => 'input',
            'placeholder' => $defaultConfig['pictureRotation'],
            'name' => 'pictureRotation',
            'value' => $config['pictureRotation'],
        ],
        'polaroid_effect' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'polaroid_effect',
            'value' => $config['polaroid_effect'],
        ],
        'polaroid_rotation' => [
            'view' => 'advanced',
            'type' => 'input',
            'placeholder' => $defaultConfig['polaroid_rotation'],
            'name' => 'polaroid_rotation',
            'value' => $config['polaroid_rotation'],
        ],
        'use_filter' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'use_filter',
            'value' => $config['use_filter'],
        ],
        'default_imagefilter' => [
            'view' => 'advanced',
            'type' => 'select',
            'name' => 'default_imagefilter',
            'placeholder' => $defaultConfig['default_imagefilter'],
            'options' => AVAILABLE_FILTERS,
            'value' => $config['default_imagefilter'],
        ],
        'disabled_filters' => [
            'view' => 'expert',
            'type' => 'multi-select',
            'name' => 'disabled_filters',
            'options' => AVAILABLE_FILTERS,
            'value' => $config['disabled_filters'],
        ],
        'take_frame' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'take_frame',
            'value' => $config['take_frame'],
        ],
        'take_frame_path' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['take_frame_path'],
            'name' => 'take_frame_path',
            'value' => htmlentities($config['take_frame_path']),
        ],
        'photo_key' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'photo_key',
            'placeholder' => '',
            'value' => $config['photo_key'],
        ],
        'file_naming' => [
            'view' => 'advanced',
            'type' => 'select',
            'name' => 'file_naming',
            'placeholder' => $defaultConfig['file_naming'],
            'options' => [
                'dateformatted' => 'Date formatted',
                'numbered' => 'Numbered',
                'random' => 'Random',
            ],
            'value' => $config['file_naming'],
        ],
        'picture_permissions' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'picture_permissions',
            'placeholder' => '0644',
            'value' => $config['picture_permissions'],
        ],
        'keep_images' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'keep_images',
            'value' => $config['keep_images'],
        ],
        'preserve_exif_data' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'preserve_exif_data',
            'value' => $config['preserve_exif_data'],
        ],
        'allow_delete' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'allow_delete',
            'value' => $config['allow_delete'],
        ],
    ],
    'collage' => [
        'view' => 'basic',
        'use_collage' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'use_collage',
            'value' => $config['use_collage'],
        ],
        'collage_cntdwn_time' => [
            'view' => 'basic',
            'type' => 'range',
            'name' => 'collage_cntdwn_time',
            'placeholder' => $defaultConfig['collage_cntdwn_time'],
            'value' => $config['collage_cntdwn_time'],
            'range_min' => 1,
            'range_max' => 10,
            'range_step' => 1,
            'unit' => 'seconds',
        ],
        'continuous_collage' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'continuous_collage',
            'value' => $config['continuous_collage'],
        ],
        'collage_layout' => [
            'view' => 'advanced',
            'type' => 'select',
            'name' => 'collage_layout',
            'placeholder' => $defaultConfig['collage_layout'],
            'options' => [
                '2x2' => '2x2',
                '2x4' => '2x4',
                '2x4BI' => '2x4 + background image',
            ],
            'value' => $config['collage_layout'],
        ],
        'collage_background' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'collage_background',
            'placeholder' => $defaultConfig['collage_background'],
            'value' => $config['collage_background'],
        ],
        'collage_key' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'collage_key',
            'placeholder' => '',
            'value' => $config['collage_key'],
        ],
        'take_collage_frame' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'take_collage_frame',
            'value' => $config['take_collage_frame'],
        ],
        'take_collage_frame_always' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'take_collage_frame_always',
            'value' => $config['take_collage_frame_always'],
        ],
        'take_collage_frame_path' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['take_collage_frame_path'],
            'name' => 'take_collage_frame_path',
            'value' => htmlentities($config['take_collage_frame_path']),
        ],
        'collage_limit' => [
            'type' => 'hidden',
            'name' => 'collage_limit',
            'value' => $config['collage_limit'],
        ],
    ],
    'gallery' => [
        'view' => 'basic',
        'show_gallery' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'show_gallery',
            'value' => $config['show_gallery'],
        ],
        'newest_first' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'newest_first',
            'value' => $config['newest_first'],
        ],
        'use_slideshow' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'use_slideshow',
            'value' => $config['use_slideshow'],
        ],
        'pictureTime' => [
            'view' => 'advanced',
            'type' => 'input',
            'placeholder' => $defaultConfig['gallery_pictureTime'],
            'name' => 'gallery_pictureTime',
            'value' => $config['gallery_pictureTime'],
        ],
        'pswp_animateTransitions' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'pswp_animateTransitions',
            'value' => $config['pswp_animateTransitions'],
        ],
        'pswp_counterEl' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'pswp_counterEl',
            'value' => $config['pswp_counterEl'],
        ],
        'pswp_history' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'pswp_history',
            'value' => $config['pswp_history'],
        ],
        'show_date' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'show_date',
            'value' => $config['show_date'],
        ],
        'date_format' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['gallery']['date_format'],
            'name' => 'gallery[date_format]',
            'value' => $config['gallery']['date_format'],
        ],
        'gallery_db_check_enabled' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'gallery_db_check_enabled',
            'value' => $config['gallery_db_check_enabled'],
        ],
        'db_check_time' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['gallery_db_check_time'],
            'name' => 'gallery_db_check_time',
            'value' => $config['gallery_db_check_time'],
        ],
        'allow_delete_from_gallery' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'allow_delete_from_gallery',
            'value' => $config['allow_delete_from_gallery'],
        ],
        'scrollbar' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'scrollbar',
            'value' => $config['scrollbar'],
        ],
        'gallery_bottom_bar' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'gallery_bottom_bar',
            'value' => $config['gallery_bottom_bar'],
        ],
        'pswp_clickToCloseNonZoomable' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'pswp_clickToCloseNonZoomable',
            'value' => $config['pswp_clickToCloseNonZoomable'],
        ],
        'pswp_closeOnScroll' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'pswp_closeOnScroll',
            'value' => $config['pswp_closeOnScroll'],
        ],
        'pswp_closeOnOutsideClick' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'pswp_closeOnOutsideClick',
            'value' => $config['pswp_closeOnOutsideClick'],
        ],
        'pswp_preventSwiping' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'pswp_preventSwiping',
            'value' => $config['pswp_preventSwiping'],
        ],
        'pswp_pinchToClose' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'pswp_pinchToClose',
            'value' => $config['pswp_pinchToClose'],
        ],
        'pswp_closeOnVerticalDrag' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'pswp_closeOnVerticalDrag',
            'value' => $config['pswp_closeOnVerticalDrag'],
        ],
        'pswp_tapToToggleControls' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'pswp_tapToToggleControls',
            'value' => $config['pswp_tapToToggleControls'],
        ],
        'pswp_zoomEl' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'pswp_zoomEl',
            'value' => $config['pswp_zoomEl'],
        ],
        'pswp_fullscreenEl' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'pswp_fullscreenEl',
            'value' => $config['pswp_fullscreenEl'],
        ],
        'pswp_loop' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'pswp_loop',
            'value' => $config['pswp_loop'],
        ],
        'pswp_bgOpacity' => [
            'view' => 'expert',
            'type' => 'range',
            'placeholder' => $defaultConfig['pswp_bgOpacity'],
            'name' => 'pswp_bgOpacity',
            'value' => $config['pswp_bgOpacity'],
            'range_min' => 0,
            'range_max' => 1,
            'range_step' => 0.05,
            'unit' => 'dot',
        ],
    ],
    'preview' => [
        'view' => 'advanced',
        'mode' => [
            'view' => 'advanced',
            'type' => 'select',
            'name' => 'preview_mode',
            'placeholder' => $defaultConfig['preview_mode'],
            'options' => [
                'none' => 'None',
                'device_cam' => 'from device cam',
                'url' => 'from URL',
                'gphoto' => 'from gphoto2',
            ],
            'value' => $config['preview_mode'],
        ],
        'preview_gphoto_bsm' => [
            'type' => 'checkbox',
            'name' => 'preview_gphoto_bsm',
            'value' => $config['preview_gphoto_bsm'],
        ],
        'previewCamTakesPic' => [
            'type' => 'checkbox',
            'name' => 'previewCamTakesPic',
            'value' => $config['previewCamTakesPic'],
        ],
        'previewCamFlipHorizontal' => [
            'type' => 'checkbox',
            'name' => 'previewCamFlipHorizontal',
            'value' => $config['previewCamFlipHorizontal'],
        ],
        'ipCamPreviewRotation' => [
            'type' => 'select',
            'name' => 'ipCamPreviewRotation',
            'placeholder' => $defaultConfig['ipCamPreviewRotation'],
            'options' => [
                '0deg' => 'No rotation',
                '90deg' => '90°',
                '-90deg' => '-90°',
                '180deg' => '180°',
                '45deg' => '45°',
                '-45deg' => '-45°',
            ],
            'value' => $config['ipCamPreviewRotation'],
        ],
        'ipCamURL' => [
            'type' => 'input',
            'name' => 'ipCamURL',
            'placeholder' => 'url(http://localhost:8081)',
            'value' => htmlentities($config['ipCamURL']),
        ],
        'videoWidth' => [
            'type' => 'input',
            'name' => 'videoWidth',
            'placeholder' => $defaultConfig['videoWidth'],
            'value' => $config['videoWidth'],
        ],
        'videoHeight' => [
            'type' => 'input',
            'name' => 'videoHeight',
            'placeholder' => $defaultConfig['videoHeight'],
            'value' => $config['videoHeight'],
        ],
        'camera_mode' => [
            'type' => 'select',
            'name' => 'camera_mode',
            'placeholder' => $defaultConfig['camera_mode'],
            'options' => [
                'user' => 'Front facing camera',
                'environment' => 'Back facing camera',
            ],
            'value' => $config['camera_mode'],
        ],
        'previewCamBackground' => [
            'type' => 'checkbox',
            'name' => 'previewCamBackground',
            'value' => $config['previewCamBackground'],
        ],
    ],
    'keying' => [
        'view' => 'advanced',
        'chroma_keying' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'chroma_keying',
            'value' => $config['chroma_keying'],
        ],
        'chroma_size' => [
            'view' => 'advanced',
            'type' => 'select',
            'name' => 'chroma_size',
            'placeholder' => $defaultConfig['chroma_size'],
            'options' => [
                '1000px' => 'S',
                '1500px' => 'M',
                '2000px' => 'L',
                '2500px' => 'XL',
            ],
            'value' => $config['chroma_size'],
        ],
        'use_live_keying' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'use_live_keying',
            'value' => $config['use_live_keying'],
        ],
        'chroma_keying_variant' => [
            'view' => 'expert',
            'type' => 'select',
            'name' => 'chroma_keying_variant',
            'placeholder' => $defaultConfig['chroma_keying_variant'],
            'options' => [
                'marvinj' => 'MarvinJ',
                'seriouslyjs' => 'Seriously.js',
            ],
            'value' => $config['chroma_keying_variant'],
        ],
        'background_path' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['keying_background_path'],
            'name' => 'keying_background_path',
            'value' => htmlentities($config['keying_background_path']),
        ],
        'live_keying_show_all' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'live_keying_show_all',
            'value' => $config['live_keying_show_all'],
        ],
    ],
    'print' => [
        'view' => 'basic',
        'cups_button' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'print_cups_button',
            'value' => $config['cups_button'],
        ],
        'use_print_result' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'print_use_print_result',
            'value' => $config['use_print_result'],
        ],
        'use_print_gallery' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'print_use_print_gallery',
            'value' => $config['use_print_gallery'],
        ],
        'use_print_chromakeying' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'print_use_print_chromakeying',
            'value' => $config['use_print_chromakeying'],
        ],
        'auto_print' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'print_auto_print',
            'value' => $config['auto_print'],
        ],
        'auto_print_delay' => [
            'view' => 'expert',
            'type' => 'range',
            'placeholder' => $defaultConfig['auto_print_delay'],
            'name' => 'auto_print_delay',
            'value' => $config['auto_print_delay'],
            'range_min' => 250,
            'range_max' => 10000,
            'range_step' => 250,
            'unit' => 'milliseconds',
        ],
        'printing_time' => [
            'view' => 'advanced',
            'type' => 'range',
            'placeholder' => $defaultConfig['printing_time'],
            'name' => 'printing_time',
            'value' => $config['printing_time'],
            'range_min' => 250,
            'range_max' => 20000,
            'range_step' => 250,
            'unit' => 'milliseconds',
        ],
        'print_key' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'print_key',
            'placeholder' => '',
            'value' => $config['print_key'],
        ],
        'print_qrcode' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'print_qrcode',
            'value' => $config['print_qrcode'],
        ],
        'print_frame' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'print_frame',
            'value' => $config['print_frame'],
        ],
        'frame_path' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['print_frame_path'],
            'name' => 'print_frame_path',
            'value' => htmlentities($config['print_frame_path']),
        ],
        'crop_onprint' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'crop_onprint',
            'value' => $config['crop_onprint'],
        ],
        'crop_width' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'crop_width',
            'placeholder' => $defaultConfig['crop_width'],
            'value' => $config['crop_width'],
        ],
        'crop_height' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'crop_height',
            'placeholder' => $defaultConfig['crop_height'],
            'value' => $config['crop_height'],
        ],
        'is_textonprint' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'is_textonprint',
            'value' => htmlentities($config['is_textonprint']),
        ],
        'line1' => [
            'view' => 'advanced',
            'type' => 'input',
            'placeholder' => $defaultConfig['textonprint']['line1'],
            'name' => 'textonprint[line1]',
            'value' => htmlentities($config['textonprint']['line1']),
        ],
        'line2' => [
            'view' => 'advanced',
            'type' => 'input',
            'placeholder' => $defaultConfig['textonprint']['line2'],
            'name' => 'textonprint[line2]',
            'value' => htmlentities($config['textonprint']['line2']),
        ],
        'line3' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['textonprint']['line3'],
            'name' => 'textonprint[line3]',
            'value' => htmlentities($config['textonprint']['line3']),
        ],
        'locationx' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['locationx'],
            'name' => 'locationx',
            'value' => $config['locationx'],
        ],
        'locationy' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['locationy'],
            'name' => 'locationy',
            'value' => $config['locationy'],
        ],
        'rotation' => [
            'view' => 'expert',
            'type' => 'range',
            'placeholder' => $defaultConfig['rotation'],
            'name' => 'rotation',
            'value' => $config['rotation'],
            'range_min' => -180,
            'range_max' => 180,
            'range_step' => 5,
            'unit' => 'degrees',
        ],
        'font_path' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['font_path'],
            'name' => 'font_path',
            'value' => htmlentities($config['font_path']),
        ],
        'fontsize' => [
            'view' => 'advanced',
            'type' => 'input',
            'placeholder' => $defaultConfig['fontsize'],
            'name' => 'fontsize',
            'value' => $config['fontsize'],
        ],
        'linespace' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['linespace'],
            'name' => 'linespace',
            'value' => $config['linespace'],
        ],
    ],
    'mail' => [
        'view' => 'basic',
        'use_mail' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'use_mail',
            'value' => $config['use_mail'],
        ],
        'send_all_later' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'send_all_later',
            'value' => $config['send_all_later'],
        ],
        'subject' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => $defaultConfig['mail_subject'],
            'name' => 'mail_subject',
            'value' => htmlentities($config['mail_subject']),
        ],
        'text' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => $defaultConfig['mail_text'],
            'name' => 'mail_text',
            'value' => htmlentities($config['mail_text']),
        ],
        'host' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => $defaultConfig['mail_host'],
            'name' => 'mail_host',
            'value' => $config['mail_host'],
        ],
        'username' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => $defaultConfig['mail_username'],
            'name' => 'mail_username',
            'value' => $config['mail_username'],
        ],
        'password' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => $defaultConfig['mail_password'],
            'name' => 'mail_password',
            'value' => htmlentities($config['mail_password']),
        ],
        'fromAddress' => [
            'view' => 'advanced',
            'type' => 'input',
            'placeholder' => $defaultConfig['mail_fromAddress'],
            'name' => 'mail_fromAddress',
            'value' => $config['mail_fromAddress'],
        ],
        'fromName' => [
            'view' => 'advanced',
            'type' => 'input',
            'placeholder' => $defaultConfig['mail_fromName'],
            'name' => 'mail_fromName',
            'value' => $config['mail_fromName'],
        ],
        'file' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['mail_file'],
            'name' => 'mail_file',
            'value' => $config['mail_file'],
        ],
        'secure' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['mail_secure'],
            'name' => 'mail_secure',
            'value' => $config['mail_secure'],
        ],
        'port' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['mail_port'],
            'name' => 'mail_port',
            'value' => $config['mail_port'],
        ],
    ],
    'slideshow' => [
        'view' => 'advanced',
        'refreshTime' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => $defaultConfig['slideshow_refreshTime'],
            'name' => 'slideshow_refreshTime',
            'value' => $config['slideshow_refreshTime'],
        ],
        'pictureTime' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => $defaultConfig['slideshow_pictureTime'],
            'name' => 'slideshow_pictureTime',
            'value' => $config['slideshow_pictureTime'],
        ],
        'randomPicture' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'slideshow_randomPicture',
            'value' => $config['slideshow_randomPicture'],
        ],
        'use_thumbs' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'slideshow_use_thumbs',
            'value' => $config['slideshow_use_thumbs'],
        ],
    ],
    'remotebuzzer' => [
        'view' => 'advanced',
        'platform' => 'linux',
        'remotebuzzer_enabled' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'remotebuzzer_enabled',
            'value' => $config['remotebuzzer_enabled'],
        ],
        'collagetime' => [
            'view' => 'advanced',
            'type' => 'range',
            'placeholder' => $defaultConfig['remotebuzzer_collagetime'],
            'name' => 'remotebuzzer_collagetime',
            'value' => $config['remotebuzzer_collagetime'],
            'range_min' => 1,
            'range_max' => 6,
            'range_step' => 1,
            'unit' => 'seconds',
        ],
        'port' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['remotebuzzer_port'],
            'name' => 'remotebuzzer_port',
            'value' => $config['remotebuzzer_port'],
        ],
        'pin' => [
            'view' => 'expert',
            'view' => 'advanced',
            'type' => 'input',
            'placeholder' => $defaultConfig['remotebuzzer_pin'],
            'name' => 'remotebuzzer_pin',
            'value' => $config['remotebuzzer_pin'],
        ],
        'logfile' => [
            'view' => 'expert',
            'type' => 'hidden',
            'name' => 'remotebuzzer_logfile',
            'value' => $config['remotebuzzer_logfile'],
        ],
    ],
    'synctodrive' => [
        'platform' => 'linux',
        'view' => 'advanced',
        'synctodrive_enabled' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'synctodrive_enabled',
            'value' => $config['synctodrive_enabled'],
        ],
        'target' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => $defaultConfig['synctodrive_target'],
            'name' => 'synctodrive_target',
            'value' => $config['synctodrive_target'],
        ],
        'interval' => [
            'view' => 'advanced',
            'type' => 'range',
            'placeholder' => $defaultConfig['synctodrive_interval'],
            'name' => 'synctodrive_interval',
            'value' => $config['synctodrive_interval'],
            'range_min' => 10,
            'range_max' => 600,
            'range_step' => 1,
            'unit' => 'seconds',
        ],
        'logfile' => [
            'view' => 'expert',
            'type' => 'hidden',
            'name' => 'synctodrive_logfile',
            'value' => $config['synctodrive_logfile'],
        ],
    ],
    'authentication' => [
        'view' => 'basic',
        'login_enabled' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'login_enabled',
            'value' => $config['login_enabled'],
        ],
        'username' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => 'Photo',
            'name' => 'login_username',
            'value' => $config['login_username'],
        ],
        'password' => [
            'view' => 'basic',
            'type' => 'input',
            'placeholder' => null,
            'name' => 'login_password',
            'value' => $config['login_password'],
        ],
        'protect_admin' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'protect_admin',
            'value' => $config['protect_admin'],
        ],
        'protect_index' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'protect_index',
            'value' => $config['protect_index'],
        ],
    ],
    'userinterface' => [
        'view' => 'basic',
        'index_style' => [
            'view' => 'basic',
            'type' => 'select',
            'name' => 'index_style',
            'placeholder' => $defaultConfig['index_style'],
            'options' => [
                'classic' => 'classic',
                'modern' => 'modern',
                'custom' => 'custom',
            ],
            'value' => $config['index_style'],
        ],
        'toggle_fs_button' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'toggle_fs_button',
            'value' => $config['toggle_fs_button'],
        ],
        'font_size' => [
            'view' => 'advanced',
            'type' => 'input',
            'name' => 'font_size',
            'placeholder' => $defaultConfig['font_size'],
            'value' => $config['font_size'],
        ],
        'colors_countdown' => [
            'view' => 'advanced',
            'type' => 'color',
            'name' => 'colors[countdown]',
            'placeholder' => $defaultConfig['colors']['countdown'],
            'value' => $config['colors']['countdown'],
        ],
        'colors_background_countdown' => [
            'view' => 'advanced',
            'type' => 'color',
            'name' => 'colors[background_countdown]',
            'placeholder' => $defaultConfig['colors']['background_countdown'],
            'value' => $config['colors']['background_countdown'],
        ],
        'colors_cheese' => [
            'view' => 'advanced',
            'type' => 'color',
            'name' => 'colors[cheese]',
            'placeholder' => $defaultConfig['colors']['cheese'],
            'value' => $config['colors']['cheese'],
        ],
        'background_image' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'background_image',
            'placeholder' => $defaultConfig['background_image'],
            'value' => htmlentities($config['background_image']),
        ],
        'background_admin' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'background_admin',
            'placeholder' => $defaultConfig['background_admin'],
            'value' => htmlentities($config['background_admin']),
        ],
        'background_chroma' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'background_chroma',
            'placeholder' => 'url(../img/bg.jpg)',
            'value' => htmlentities($config['background_chroma']),
        ],
        'rounded_corners' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'rounded_corners',
            'value' => $config['rounded_corners'],
        ],
        'colors_primary' => [
            'view' => 'expert',
            'type' => 'color',
            'name' => 'colors[primary]',
            'placeholder' => $defaultConfig['colors']['primary'],
            'value' => $config['colors']['primary'],
        ],
        'colors_secondary' => [
            'view' => 'expert',
            'type' => 'color',
            'name' => 'colors[secondary]',
            'placeholder' => $defaultConfig['colors']['secondary'],
            'value' => $config['colors']['secondary'],
        ],
        'colors_font' => [
            'view' => 'expert',
            'type' => 'color',
            'name' => 'colors[font]',
            'placeholder' => $defaultConfig['colors']['font'],
            'value' => $config['colors']['font'],
        ],
        'colors_button_font' => [
            'view' => 'expert',
            'type' => 'color',
            'name' => 'colors[button_font]',
            'placeholder' => $defaultConfig['colors']['button_font'],
            'value' => $config['colors']['button_font'],
        ],
        'colors_start_font' => [
            'view' => 'expert',
            'type' => 'color',
            'name' => 'colors[start_font]',
            'placeholder' => $defaultConfig['colors']['start_font'],
            'value' => $config['colors']['start_font'],
        ],
        'colors_panel' => [
            'view' => 'expert',
            'type' => 'color',
            'name' => 'colors[panel]',
            'placeholder' => $defaultConfig['colors']['panel'],
            'value' => $config['colors']['panel'],
        ],
        'colors_hover_panel' => [
            'view' => 'expert',
            'type' => 'color',
            'name' => 'colors[hover_panel]',
            'placeholder' => $defaultConfig['colors']['hover_panel'],
            'value' => $config['colors']['hover_panel'],
        ],
        'colors_border' => [
            'view' => 'expert',
            'type' => 'color',
            'name' => 'colors[border]',
            'placeholder' => $defaultConfig['colors']['border'],
            'value' => $config['colors']['border'],
        ],
        'colors_box' => [
            'view' => 'expert',
            'type' => 'color',
            'name' => 'colors[box]',
            'placeholder' => $defaultConfig['colors']['box'],
            'value' => $config['colors']['box'],
        ],
        'colors_gallery_button' => [
            'view' => 'expert',
            'type' => 'color',
            'name' => 'colors[gallery_button]',
            'placeholder' => $defaultConfig['colors']['gallery_button'],
            'value' => $config['colors']['gallery_button'],
        ],
    ],
    'jpeg_quality' => [
        'view' => 'expert',
        'jpeg_quality_image' => [
            'view' => 'expert',
            'type' => 'range',
            'name' => 'jpeg_quality_image',
            'placeholder' => $defaultConfig['jpeg_quality_image'],
            'value' => $config['jpeg_quality_image'],
            'range_min' => -1,
            'range_max' => 100,
            'range_step' => 1,
            'unit' => 'percent',
        ],
        'jpeg_quality_chroma' => [
            'view' => 'expert',
            'type' => 'range',
            'name' => 'jpeg_quality_chroma',
            'placeholder' => $defaultConfig['jpeg_quality_chroma'],
            'value' => $config['jpeg_quality_chroma'],
            'range_min' => 10,
            'range_max' => 100,
            'range_step' => 1,
            'unit' => 'percent',
        ],
        'jpeg_quality_thumb' => [
            'view' => 'expert',
            'type' => 'range',
            'name' => 'jpeg_quality_thumb',
            'placeholder' => $defaultConfig['jpeg_quality_thumb'],
            'value' => $config['jpeg_quality_thumb'],
            'range_min' => 10,
            'range_max' => 100,
            'range_step' => 1,
            'unit' => 'percent',
        ],
    ],
    'commands' => [
        'view' => 'expert',
        'take_picture_cmd' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['take_picture']['cmd'],
            'name' => 'take_picture[cmd]',
            'value' => htmlentities($config['take_picture']['cmd']),
        ],
        'take_picture_msg' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['take_picture']['msg'],
            'name' => 'take_picture[msg]',
            'value' => htmlentities($config['take_picture']['msg']),
        ],
        'print_cmd' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['print']['cmd'],
            'name' => 'print[cmd]',
            'value' => htmlentities($config['print']['cmd']),
        ],
        'print_msg' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['print']['msg'],
            'name' => 'print[msg]',
            'value' => htmlentities($config['print']['msg']),
        ],
        'exiftool_cmd' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['exiftool']['cmd'],
            'name' => 'exiftool[cmd]',
            'value' => htmlentities($config['exiftool']['cmd']),
        ],
        'exiftool_msg' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['exiftool']['msg'],
            'name' => 'exiftool[msg]',
            'value' => htmlentities($config['exiftool']['msg']),
        ],
        'preview_cmd' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['preview']['cmd'],
            'name' => 'preview[cmd]',
            'value' => htmlentities($config['preview']['cmd']),
        ],
        'preview_killcmd' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['preview']['killcmd'],
            'name' => 'preview[killcmd]',
            'value' => htmlentities($config['preview']['killcmd']),
        ],
        'nodebin_cmd' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['nodebin']['cmd'],
            'name' => 'nodebin[cmd]',
            'value' => htmlentities($config['nodebin']['cmd']),
        ],
    ],
    'folders' => [
        'view' => 'expert',
        'data' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['folders']['data'],
            'name' => 'folders[data]',
            'value' => $config['folders']['data'],
        ],
        'images' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['folders']['images'],
            'name' => 'folders[images]',
            'value' => $config['folders']['images'],
        ],
        'keying' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['folders']['keying'],
            'name' => 'folders[keying]',
            'value' => $config['folders']['keying'],
        ],
        'print' => [
            'view' => 'expert',
            'type' => 'input',
            'name' => 'folders[print]',
            'placeholder' => $defaultConfig['folders']['print'],
            'value' => $config['folders']['print'],
        ],
        'qrcodes' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['folders']['qrcodes'],
            'name' => 'folders[qrcodes]',
            'value' => $config['folders']['qrcodes'],
        ],
        'thumbs' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['folders']['thumbs'],
            'name' => 'folders[thumbs]',
            'value' => $config['folders']['thumbs'],
        ],
        'tmp' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['folders']['tmp'],
            'name' => 'folders[tmp]',
            'value' => $config['folders']['tmp'],
        ],
        'archives' => [
            'view' => 'expert',
            'type' => 'input',
            'placeholder' => $defaultConfig['folders']['archives'],
            'name' => 'folders[archives]',
            'value' => $config['folders']['archives'],
        ],
    ],
    'reset' => [
        'view' => 'basic',
        'remove_images' => [
            'view' => 'basic',
            'type' => 'checkbox',
            'name' => 'reset_remove_images',
            'value' => $config['reset_remove_images'],
        ],
        'remove_mailtxt' => [
            'view' => 'advanced',
            'type' => 'checkbox',
            'name' => 'reset_remove_mailtxt',
            'value' => $config['reset_remove_mailtxt'],
        ],
        'remove_config' => [
            'view' => 'expert',
            'type' => 'checkbox',
            'name' => 'reset_remove_config',
            'value' => $config['reset_remove_config'],
        ],
    ],
];
