<?php

namespace Photobooth\Configuration\Section;

use Symfony\Component\Config\Definition\Builder\NodeDefinition;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;

final class PrintConfiguration
{
    public static function getNode(): NodeDefinition
    {
        return (new TreeBuilder('print'))->getRootNode()->addDefaultsIfNotSet()
            ->ignoreExtraKeys()
            ->children()
                ->booleanNode('from_result')->defaultValue(false)->end()
                ->booleanNode('from_gallery')->defaultValue(false)->end()
                ->booleanNode('from_chromakeying')->defaultValue(false)->end()
                ->booleanNode('auto')->defaultValue(false)->end()
                ->integerNode('auto_delay')
                    ->min(250)
                    ->max(10000)
                    ->defaultValue(1000)
                    ->beforeNormalization()
                        ->ifString()
                        ->then(function (string $value): int { return intval($value); })
                        ->end()
                    ->end()
                ->integerNode('time')
                    ->min(500)
                    ->max(60000)
                    ->defaultValue(5000)
                    ->beforeNormalization()
                        ->ifString()
                        ->then(function (string $value): int { return intval($value); })
                        ->end()
                    ->end()
                ->integerNode('max_multi')
                    ->min(1)
                    ->max(10)
                    ->defaultValue(1)
                    ->beforeNormalization()
                        ->ifString()
                        ->then(function (string $value): int { return intval($value); })
                        ->end()
                    ->end()
                ->integerNode('limit')
                    ->defaultValue(0)
                    ->beforeNormalization()
                        ->ifString()
                        ->then(function (string $value): int { return intval($value); })
                        ->end()
                    ->end()
                ->scalarNode('locking_msg')->defaultValue('Printing... Print limit reached, print will be locked.')->end()
                ->scalarNode('limit_msg')->defaultValue('Print locked.')->end()
                ->booleanNode('no_rotate')->defaultValue(false)->end()
                ->scalarNode('key')->defaultValue('')->end()
                ->booleanNode('qrcode')->defaultValue(false)->end()
                ->integerNode('qrSize')
                    ->defaultValue(4)
                    ->min(4)
                    ->max(10)
                    ->beforeNormalization()
                        ->ifString()
                        ->then(function (string $value): int { return intval($value); })
                        ->end()
                    ->end()
                ->enumNode('qrPosition')
                    ->values(['topLeft', 'top', 'topRight', 'right', 'bottomRight', 'bottom', 'bottomLeft', 'left'])
                    ->defaultValue('bottomRight')
                    ->end()
                ->integerNode('qrOffset')
                    ->defaultValue(10)
                    ->beforeNormalization()
                        ->ifString()
                        ->then(function (string $value): int { return intval($value); })
                        ->end()
                    ->end()
                ->integerNode('qrMargin')
                    ->defaultValue(4)
                    ->min(0)
                    ->max(10)
                    ->beforeNormalization()
                        ->ifString()
                        ->then(function (string $value): int { return intval($value); })
                        ->end()
                    ->end()
                ->scalarNode('qrBgColor')->defaultValue('#ffffff')->end()
                ->booleanNode('print_frame')->defaultValue(false)->end()
                ->scalarNode('frame')->defaultValue('')->end()
                ->booleanNode('crop')->defaultValue(false)->end()
                ->integerNode('crop_width')
                    ->defaultValue(1000)
                    ->beforeNormalization()
                        ->ifString()
                        ->then(function (string $value): int { return intval($value); })
                        ->end()
                    ->end()
                ->integerNode('crop_height')
                    ->defaultValue(500)
                    ->beforeNormalization()
                        ->ifString()
                        ->then(function (string $value): int { return intval($value); })
                        ->end()
                    ->end()
            ->end();
    }
}
