parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Photobooth\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Photobooth\Twig\Extension\GlobalVariablesExtension:
      arguments: ["%photobooth.config%"]
      tags:
        - name: twig.extension
