---
# vim: set ft=yaml.ansible:
#
- name: Install lighttpd packages
  ansible.builtin.package:
    name: '{{ lighttpd_packages }}'
    state: installed
  notify: Restart lighttpd

- name: Copy configuration
  ansible.builtin.template:
    src: fastcgi.conf.j2
    dest: /etc/lighttpd/conf-available/15-fastcgi-php.conf
    mode: '0644'

- name: Enable lighttpd mods
  ansible.builtin.command:
    cmd: lighttpd-enable-mod {{ item }} && touch /etc/lighttpd/.{{ item }}
    creates: /etc/lighttpd/.{{ item }}
  loop: '{{ lighttpd_mods }}'
  notify: Restart lighttpd
