<?php
    include("checkbox.php");
    include("colorInput.php");
    include("inputButton.php");
    include("headline.php");
    include("rangeInput.php");
    include("select.php");
    include("textInput.php");
?>