name: Build and upload package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Pack zip
        run: npm run pack:build

      - name: Publish zip
        uses: actions/upload-artifact@v3
        with:
          name: photobooth
          path: archives/photobooth-*.zip

      - name: Remove archives folder
        run: rm -rf archives
