name: Shellcheck 

on:
  push:
    branches:
      - dev
      - stable4
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches:
      - dev
      - stable4
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Shellcheck
        run: |
          shellcheck install-photobooth.sh
          shellcheck scripts/*.sh
          shellcheck scripts/gphoto/*.sh
